force-app/main/default/objects/Protocol_Option__c/Protocol_Option__c.object-meta.xml
<CustomObject>
    <label>Protocol Option</label>
    <nameField>
        <displayFormat>PO - {000000}</displayFormat>
        <label>Protocol Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protocol Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol_Option__c/fields/Protocol_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Item_Type__c</fullName>
    <label>Protocol Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Protocol_Option__c/fields/Protocol_Option__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Option__c</fullName>
    <label>Protocol Option</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Protocol_Item_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incident - PI-MV-EE</fullName>
            </value>
            <value>
                <fullName>Incident - PI-MV-AO</fullName>
            </value>
            <value>
                <fullName>Incident - PI-EL-EE</fullName>
            </value>
            <value>
                <fullName>Incident - PI-PL-EE</fullName>
            </value>
            <value>
                <fullName>Claimant - PI-MV-EE</fullName>
            </value>
            <value>
                <fullName>Claimant - PI-MV-AO</fullName>
            </value>
            <value>
                <fullName>Claimant - PI-EL-EE</fullName>
            </value>
            <value>
                <fullName>Claimant - PI-PL-EE</fullName>
            </value>
            <value>
                <fullName>Defendant - PI-MV-EE</fullName>
            </value>
            <value>
                <fullName>Defendant - PI-MV-AO</fullName>
            </value>
            <value>
                <fullName>Defendant - PI-EL-EE</fullName>
            </value>
            <value>
                <fullName>Defendant - PI-PL-EE</fullName>
            </value>
            <value>
                <fullName>Case - PI-MV-EE</fullName>
            </value>
            <value>
                <fullName>Case - PI-MV-AO</fullName>
            </value>
            <value>
                <fullName>Case - PI-EL-EE</fullName>
            </value>
            <value>
                <fullName>Case - PI-PL-EE</fullName>
            </value>
            <value>
                <fullName>Case Arbribtration</fullName>
                <isActive>false</isActive>
                <label>Case Arbribtration</label>
            </value>
            <value>
                <fullName>Case EndtoEnd</fullName>
                <isActive>false</isActive>
                <label>Case EndtoEnd</label>
            </value>
            <value>
                <fullName>Claimant Arbitration</fullName>
                <isActive>false</isActive>
                <label>Claimant Arbitration</label>
            </value>
            <value>
                <fullName>Claimant EndtoEnd</fullName>
                <isActive>false</isActive>
                <label>Claimant EndtoEnd</label>
            </value>
            <value>
                <fullName>Defendant Arbitration</fullName>
                <isActive>false</isActive>
                <label>Defendant Arbitration</label>
            </value>
            <value>
                <fullName>Defendant EndtoEnd</fullName>
                <isActive>false</isActive>
                <label>Defendant EndtoEnd</label>
            </value>
            <value>
                <fullName>Incident Arbitration</fullName>
                <isActive>false</isActive>
                <label>Incident Arbitration</label>
            </value>
            <value>
                <fullName>Incident EndtoEnd</fullName>
                <isActive>false</isActive>
                <label>Incident EndtoEnd</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_InsertProtocolOptions.cls
Public Class Test_InsertProtocolOptions{



  public static void InsertProtocolOptions() {
        
        
        //Claimant
        Protocol_Option__c testProtocolOptionClaimantType1 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Claimant',
                                                                                     Protocol_Option__c = 'Claimant - PI-MV-EE'
        );
        insert testProtocolOptionClaimantType1;
        
        Protocol_Option__c testProtocolOptionClaimantType2 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Claimant',
                                                                                     Protocol_Option__c = 'Claimant - PI-MV-AO'
        );
        insert testProtocolOptionClaimantType2;
        
        Protocol_Option__c testProtocolOptionClaimantType3 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Claimant',
                                                                                     Protocol_Option__c = 'Claimant - PI-EL-EE'
        );
        insert testProtocolOptionClaimantType3;
        Protocol_Option__c testProtocolOptionClaimantType4 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Claimant',
                                                                                     Protocol_Option__c = 'Claimant - PI-PL-EE'
        );
        insert testProtocolOptionClaimantType4;
        
        
        
        
        
        //Defendant
        Protocol_Option__c testProtocolOptionDefendantType1 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Defendant',
                                                                         Protocol_Option__c = 'Defendant - PI-MV-EE'
        );
        insert testProtocolOptionDefendantType1;
        Protocol_Option__c testProtocolOptionDefendantType2 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Defendant',
                                                                         Protocol_Option__c = 'Defendant - PI-MV-AO'
        );
        insert testProtocolOptionDefendantType2;
        Protocol_Option__c testProtocolOptionDefendantType3 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Defendant',
                                                                         Protocol_Option__c = 'Defendant - PI-EL-EE'
        );
        insert testProtocolOptionDefendantType3;
        Protocol_Option__c testProtocolOptionDefendantType4 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Defendant',
                                                                         Protocol_Option__c = 'Defendant - PI-PL-EE'
        );
        insert testProtocolOptionDefendantType4;
        
        
        
        
        //Incident
        Protocol_Option__c testProtocolOptionIncidentType1 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Incident',
                                                                         Protocol_Option__c = 'Incident - PI-MV-EE'
        );
        insert testProtocolOptionIncidentType1;
        Protocol_Option__c testProtocolOptionIncidentType2 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Incident',
                                                                         Protocol_Option__c = 'Incident - PI-MV-AO'
        );
        insert testProtocolOptionIncidentType2;
        Protocol_Option__c testProtocolOptionIncidentType3 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Incident',
                                                                         Protocol_Option__c = 'Incident - PI-EL-EE'
        );
        insert testProtocolOptionIncidentType3;
        Protocol_Option__c testProtocolOptionIncidentType4 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Incident',
                                                                         Protocol_Option__c = 'Incident - PI-PL-EE'
        );
        insert testProtocolOptionIncidentType4;
         
        
        //Case
        
        Protocol_Option__c testProtocolOptionCaseType1 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Case',
                                                                         Protocol_Option__c = 'Case - PI-MV-EE'
        );
        Insert testProtocolOptionCaseType1;
        Protocol_Option__c testProtocolOptionCaseType2 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Case',
                                                                         Protocol_Option__c = 'Case - PI-MV-AO'
        );
        Insert testProtocolOptionCaseType2;
        Protocol_Option__c testProtocolOptionCaseType3 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Case',
                                                                         Protocol_Option__c = 'Case - PI-EL-EE'
        );
        Insert testProtocolOptionCaseType3;
        Protocol_Option__c testProtocolOptionCaseType4 = new  Protocol_Option__c (Protocol_Item_Type__c = 'Case',
                                                                         Protocol_Option__c = 'Case - PI-PL-EE'
        );
        Insert testProtocolOptionCaseType4;
        
        
 }
 
 
 }