force-app/main/default/objects/Case/fields/Agree_to_Arbitration_Process__c.field-meta.xml
<CustomField>
    <fullName>Agree_to_Arbitration_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimant - Agree to Arbitration Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitration_Completed_Count__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Completed_Count__c</fullName>
    <label>Neg-Arb-4-Arbitration Completed Count</label>
    <summarizedField>Loss_Category__c.Confirm_Case_Settlement__c</summarizedField>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitration_Firm__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arbitration Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Arbitration Firm)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitration_Negotiation_Count__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Negotiation_Count__c</fullName>
    <label>Neg-Arb-3-Arbitration Negotiation Count</label>
    <summarizedField>Loss_Category__c.Arbitration_Negotiation_Count__c</summarizedField>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitrator_Contact__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arbitrator Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Arbitration_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Arbitrator Contact)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Claimant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__c</field>
            <operation>equals</operation>
            <valueField>$Source.ClaimantFirm__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Claimant_Minimum_Personal_Details__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Minimum_Personal_Details__c</fullName>
    <label>Reg-Created-3-Claimant Personal Details</label>
    <summaryFilterItems>
        <field>Claimant_Information__c.Claimant_Date_of_Birth__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Claimant_Information__c.Claimant_First_Name__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Claimant_Information__c.Claimant_Last_Name__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>Claimant_Information__c.Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/ClaimantFirm__c.field-meta.xml
<CustomField>
    <fullName>ClaimantFirm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Claimant Firm)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Accept_Reject__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Accept_Reject__c</fullName>
    <label>Defendant Accept/Reject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Agree_to_Arbitration_Process__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Agree_to_Arbitration_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant - Agree to Arbitration Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Defendant Firm</inlineHelpText>
    <label>Defendant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Defendant Firm)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Defendant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Defendant_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases (Defendant Firm Team)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Minimum_Personal_Details__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Minimum_Personal_Details__c</fullName>
    <description>Defendant Minimum Personal Details</description>
    <label>Created-Reg-4-Defendant Min Detail</label>
    <summaryFilterItems>
        <field>Defendant_Information__c.Minimum_requirements__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Defendant_Information__c.Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendent_rejection_reason__c.field-meta.xml
<CustomField>
    <fullName>Defendent_rejection_reason__c</fullName>
    <label>Defendent rejection reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facilitator_Contact__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Facilitator_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Facilitator Contact)</relationshipLabel>
    <relationshipName>Facilitator_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facilitator_Firm__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Facilitator Firm)</relationshipLabel>
    <relationshipName>Facilitator_Firm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invite_Arbitrator__c.field-meta.xml
<CustomField>
    <fullName>Invite_Arbitrator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invite Arbitrator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Settled_Status_Count__c.field-meta.xml
<CustomField>
    <fullName>Settled_Status_Count__c</fullName>
    <label>Neg-PS-2-Settled Status Count</label>
    <summarizedField>Loss_Category__c.Settled_Status_Count__c</summarizedField>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Settlement_Negotiation_Status_Count__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Negotiation_Status_Count__c</fullName>
    <label>Neg-PS-1-Settlement Neg Status Count</label>
    <summarizedField>Loss_Category__c.Negotiation_Status_Count__c</summarizedField>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registration</fullName>
                <default>true</default>
                <label>Registration</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Finalize</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Arbitrating</fullName>
                <isActive>false</isActive>
                <label>Arbitrating</label>
            </value>
            <value>
                <fullName>Closed Awarded</fullName>
                <isActive>false</isActive>
                <label>Closed Awarded</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Submit_Case__c.field-meta.xml
<CustomField>
    <fullName>Submit_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Submit_Schedule_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Submit_Schedule_of_Losses__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit Schedule of Losses- Claimant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Submit_Schedule_of_Losses_Defendant__c.field-meta.xml
<CustomField>
    <fullName>Submit_Schedule_of_Losses_Defendant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit Schedule of Losses- Defendant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Defendant_Firm__c/Defendant_Firm__c.object-meta.xml
<CustomObject>
    <label>Defendant Firm</label>
    <nameField>
        <displayFormat>Defendant Firm - {00000}</displayFormat>
        <label>Defendant Firm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defendant Firms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Defendant_Firm__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Defendant Firms</relationshipLabel>
    <relationshipName>Defendant_Firms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/Schedule_of_Losses__c.object-meta.xml
<CustomObject>
    <label>Schedule of Losses</label>
    <nameField>
        <displayFormat>Sched {00000}</displayFormat>
        <label>Schedule of Losses No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Schedule of Losses</relationshipLabel>
    <relationshipName>Schedule_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Invite_Arbitrator__c.field-meta.xml
<CustomField>
    <fullName>Invite_Arbitrator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invite Arbitrator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NotifyDefendantTeamSubmitDocumentsSOL.cls
Public Class NotifyDefendantTeamSubmitDocumentsSOL{

    @invocablemethod
    Public static void NotifyClaimantTeamAcceptDeclineSOL(List<Id> SOLId){
      
            Schedule_of_Losses__c[] ScheduleLosses = [Select id,Case__c From Schedule_of_Losses__c Where id in:SOLId];  
              
            Set<String> Set_Case = new Set<String>();  
            for(Schedule_of_Losses__c s:ScheduleLosses){
                Set_Case.add(s.Case__c);
            }  
              
            Case[]  CaseQuick = [Select id,Invite_Arbitrator__c,Status,Settled_Status_Count__c ,Arbitrator_Contact__c ,Arbitration_Completed_Count__c ,Arbitration_Negotiation_Count__c,Settlement_Negotiation_Status_Count__c,Submit_Schedule_of_Losses__c,Submit_Case__c,Defendent_rejection_reason__c ,Stage__c,Defendant_Agree_to_Arbitration_Process__c,Defendant_Accept_Reject__c ,Submit_Schedule_of_Losses_Defendant__c,Arbitration_Firm__c,Agree_to_Arbitration_Process__c, Claimant_Firm_Team__c,ClaimantFirm__c,Claimant_Minimum_Personal_Details__c,Defendant_Minimum_Personal_Details__c,Facilitator_Firm__c,Facilitator_Contact__c,Defendant_Firm_Team__c,Defendant_Firm__c,Total_Obligation__c,Protocol__r.Mininmum_Schedule__c,Merit_Minimum_Requirements__c from Case Where id in:Set_Case]; //CQuick.Id
             
            for(Case   c:CaseQuick){ 
                CaseNotificationHandler.NotifyTeamMembersRegistration(c.Defendant_Firm_Team__c,'Defendant',c.id,'SubmitDocuments');
            }    
    }
    //Defendant_Firm_Team__c
}