force-app/main/default/objects/Case/fields/Arbitrator_Accept_Decline__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Accept_Decline__c</fullName>
    <inlineHelpText>Arbitrator responds to invitation to arbitrate case</inlineHelpText>
    <label>Arbitrator Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitrator_Contact__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arbitrator Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Arbitration_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Arbitrator Contact)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facilitator_Contact__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Facilitator_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Facilitator Contact)</relationshipLabel>
    <relationshipName>Facilitator_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facilitator_Firm__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Facilitator Firm)</relationshipLabel>
    <relationshipName>Facilitator_Firm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invite_Arbitrator__c.field-meta.xml
<CustomField>
    <fullName>Invite_Arbitrator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invite Arbitrator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Handler</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Arbitrator</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UserAccessRights_test.cls
@istest

Public class UserAccessRights_test{

 
Public static testmethod void UserAccessRights1(){

    test.starttest();
    
            
           // Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
          //  Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
         //   Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
           Test_InsertFirm_Contact_Team_TeamRole_2.insertContactUser();
            
            Test_SetUpCaseProtocol_3.testCreateProtocol();
   
    User[] user1 = [Select id From User where username='handler4@testINAP.com']; 
    
    
    Case cs = [Select id from Case limit 1];
    System.runAs(user1[0]) {
              UserAccessRights.UserRightsLossItems(cs.Id);
    }
    
    
    user1 = [Select id From User where username='handler3@testINAP.com']; 
  
    System.runAs(user1[0]) {
              UserAccessRights.UserRightsLossItems(cs.Id);
    }
    
    
    

}

Public static testmethod void UserAccessRights2(){

    test.starttest();
    
      //      Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
      //      Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
      //      Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
      Test_InsertFirm_Contact_Team_TeamRole_2.insertContactUser();
            
      Test_SetUpCaseProtocol_3.testCreateProtocol();
   
    User[] user1 = [Select id From User where username='handler4@testINAP.com']; 
    
    
    Case cs = [Select id from Case limit 1];
  
    System.runAs(user1[0]) {
              UserAccessRights.UserRightsLossItems(cs.Id);
    }
      
      
    user1 = [Select id From User where username='supervisor2@testINAP.com']; 
  
    System.runAs(user1[0]) {
              UserAccessRights.UserRightsLossItems(cs.Id);
    }
     
    UserAccessRights.UserRightsLossItems(cs.Id);
    test.stoptest();
    

} 

Public static testmethod void UserAccessRights2b(){

    test.starttest();
    
             
         //   Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
        //    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
       //     Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
         Test_InsertFirm_Contact_Team_TeamRole_2.insertContactUser();   
            Test_SetUpCaseProtocol_3.testCreateProtocol();
   
    User[] user1 = [Select id From User where username='handler5@testINAP.com']; 
    
    
    Case cs = [Select id from Case limit 1];
  
    System.runAs(user1[0]) {
              UserAccessRights.UserRightsLossItems(cs.Id);
    }
      
      
    user1 = [Select id From User where username='supervisor7@testINAP.com']; 
  
    System.runAs(user1[0]) {
              UserAccessRights.UserRightsLossItems(cs.Id);
    }
     
    UserAccessRights.UserRightsLossItems(cs.Id);
    test.stoptest();
    

}



 
Public static testmethod void UserAccessRights4(){

    test.starttest();
    
           
        //    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
            
            
            Test_SetUpCaseProtocol_1.testCreateProtocol();
   
     
        
    Case cs = [Select id,Facilitator_Firm__c,Facilitator_Contact__c from Case limit 1];
  
       
    Contact[] Facilitator = [Select id from Contact where Role__c = 'Facilitator'];            
       
                     
    cs.Facilitator_Contact__c = Facilitator[0].id;           
    update cs;
     
     
    User[] user1 = [Select id From User where username='facilitate@noemail.com']; 
    
    
    System.runAs(user1[0]) {
              UserAccessRights.UserRightsLossItems(cs.Id);
    }
     
    
    test.stoptest();
    

} 
 
Public static testmethod void UserAccessRights3(){

    test.starttest();
    
            
         //   Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
            
            Test_SetUpCaseProtocol_1a.testCreateProtocol();
   
     
     
        
    Case cs = [Select id,Invite_Arbitrator__c,Arbitrator_Contact__c from Case limit 1];
  
       
           
            
    Contact[] Arbitrator = [Select id from Contact where Role__c = 'Arbitrator'];
     cs.Invite_Arbitrator__c = true;                 
     cs.Arbitrator_Contact__c = Arbitrator[0].id;            
           
    cs.Arbitrator_Accept_Decline__c='Accept';
            
    update cs;  
            
    User[] user1 = [Select id From User where username='Arbitrate@noemail.com'];
    System.runAs(user1[0]) {
              UserAccessRights.UserRightsLossItems(cs.Id);
    }
      
      
   
     
    
    test.stoptest();
    

}
 

}