force-app/main/default/objects/Case/fields/Arbitrator_Contact__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arbitrator Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Arbitration_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Arbitrator Contact)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facilitator_Contact__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Facilitator_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Facilitator Contact)</relationshipLabel>
    <relationshipName>Facilitator_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddArbitratorTeam.cls
Public Class AddArbitratorTeam{


@InvocableMethod
Public Static void AddArbitratorTeam(List<Id> ArbitratorId){
       
    Case[] Lst_Case = [Select id,Arbitrator_Contact__c From Case Where id in: ArbitratorId];
    
    Map<String,String> Map_TeamIdCaseId = new Map<String,String>();
    
    Set<String> Set_ContactId = new Set<String>();
    for(Case c:Lst_Case){
         // Set_ContactId.add(c.Facilitator_Contact__c);
          Map_TeamIdCaseId.put(c.Arbitrator_Contact__c,c.id);  
    }
    
    system.Debug('****'+Map_TeamIdCaseId);
    
    CaseMemberHandler.AddtoCaseTeamIndividual('Arbitrator',Map_TeamIdCaseId);
    //FirmMemberTeamHandler.AddCountupdateIndividual(Set_ContactId);
}
    
}