force-app/main/default/objects/Case/fields/Arbitration_Completed_Count__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Completed_Count__c</fullName>
    <label>Neg-Arb-4-Arbitration Completed Count</label>
    <summarizedField>Loss_Category__c.Confirm_Case_Settlement__c</summarizedField>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitration_Final_Offers_Count__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Final_Offers_Count__c</fullName>
    <label>Neg-Arb-1-Arbitration Final Offers</label>
    <summaryFilterItems>
        <field>Loss_Category__c.Arbitration_Final_Offers_Count__c</field>
        <operation>greaterOrEqual</operation>
        <value>1</value>
    </summaryFilterItems>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitration_Negotiation_Count__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Negotiation_Count__c</fullName>
    <label>Neg-Arb-3-Arbitration Negotiation Count</label>
    <summarizedField>Loss_Category__c.Arbitration_Negotiation_Count__c</summarizedField>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitration_Prep_Count__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Prep_Count__c</fullName>
    <label>Neg-Neg-10-Arbitration Prep Count</label>
    <summaryFilterItems>
        <field>Loss_Category__c.Arbitration_Prep_Count__c</field>
        <operation>greaterOrEqual</operation>
        <value>1</value>
    </summaryFilterItems>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Claimant_Confirms_Case_Settled__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Confirms_Case_Settled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimant Confirms Case Settled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Merit_Arbitrated_Count__c.field-meta.xml
<CustomField>
    <fullName>Merit_Arbitrated_Count__c</fullName>
    <label>Neg-Neg-Merit Arbitrated Count</label>
    <summaryFilterItems>
        <field>Merit__c.Status__c</field>
        <operation>equals</operation>
        <value>Arbitrated</value>
    </summaryFilterItems>
    <summaryForeignKey>Merit__c.Related_Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Merit_Arbitration_Count__c.field-meta.xml
<CustomField>
    <fullName>Merit_Arbitration_Count__c</fullName>
    <label>Neg-Neg-Merit Arbitration Count</label>
    <summaryFilterItems>
        <field>Merit__c.Status__c</field>
        <operation>equals</operation>
        <value>Arbitration Doc Prep,Arbitration Final Offers, Arbitrating</value>
    </summaryFilterItems>
    <summaryForeignKey>Merit__c.Related_Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Merit_Negotiation_Count__c.field-meta.xml
<CustomField>
    <fullName>Merit_Negotiation_Count__c</fullName>
    <label>Neg-Neg-Merit Negotiation Count</label>
    <summaryFilterItems>
        <field>Merit__c.Status__c</field>
        <operation>equals</operation>
        <value>Negotiating</value>
    </summaryFilterItems>
    <summaryForeignKey>Merit__c.Related_Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Merit_Settled_Count__c.field-meta.xml
<CustomField>
    <fullName>Merit_Settled_Count__c</fullName>
    <label>Neg-Neg-Merit Settled Count</label>
    <summaryFilterItems>
        <field>Merit__c.Status__c</field>
        <operation>equals</operation>
        <value>Settled</value>
    </summaryFilterItems>
    <summaryForeignKey>Merit__c.Related_Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Payment_Obligation_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Payment_Obligation_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Obligation Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Protocol__c.field-meta.xml
<CustomField>
    <fullName>Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Refer_to_Arbitration_Count__c.field-meta.xml
<CustomField>
    <fullName>Refer_to_Arbitration_Count__c</fullName>
    <label>Neg-Neg-8-Refer to Arbitration Count</label>
    <summaryFilterItems>
        <field>Loss_Category__c.Refer_to_Arbitration_Count__c</field>
        <operation>greaterOrEqual</operation>
        <value>1</value>
    </summaryFilterItems>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Settled_Status_Count__c.field-meta.xml
<CustomField>
    <fullName>Settled_Status_Count__c</fullName>
    <label>Neg-PS-2-Settled Status Count</label>
    <summarizedField>Loss_Category__c.Settled_Status_Count__c</summarizedField>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Settlement_Negotiation_Status_Count__c.field-meta.xml
<CustomField>
    <fullName>Settlement_Negotiation_Status_Count__c</fullName>
    <label>Neg-PS-1-Settlement Neg Status Count</label>
    <summarizedField>Loss_Category__c.Negotiation_Status_Count__c</summarizedField>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Total_Loss_Item_Count__c.field-meta.xml
<CustomField>
    <fullName>Total_Loss_Item_Count__c</fullName>
    <label>Neg-Neg-1-Total Loss Item Count</label>
    <summarizedField>Loss_Category__c.Loss_Item_Count__c</summarizedField>
    <summaryForeignKey>Loss_Category__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NotifyDefendantFINALAWARDCase_test.cls
@istest

Public class NotifyDefendantFINALAWARDCase_test{


Public static testmethod void NotifyDefendantFINALAWARDCase1(){

    test.starttest();
          // Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPARB2@noemail.com','ARB2');
            
          //  Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
           // Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
           // Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
            Test_InsertFirm_Contact_Team_TeamRole_2.insertContactUser();  
            Test_SetUpCaseProtocol_5.testCreateProtocol();
            
             Case[] testCase = [Select Settled_Status_Count__c,Protocol__r.Name,Settlement_Negotiation_Status_Count__c,Merit_Settled_Count__c,Merit_Negotiation_Count__c,Merit_Arbitration_Count__c,Merit_Arbitrated_Count__c,Refer_to_Arbitration_Count__c,Total_Loss_Item_Count__c,Arbitration_Prep_Count__c,Arbitration_Final_Offers_Count__c,Arbitration_Negotiation_Count__c,Arbitration_Completed_Count__c,Claimant_Confirms_Case_Settled__c,Payment_Obligation_Email_Sent__c from Case];
             testCase[0].Claimant_Confirms_Case_Settled__c = true;
             testCase[0].Payment_Obligation_Email_Sent__c = true;
              /*
             System.debug('**Settled_Status_Count***'+testCase[0].Settled_Status_Count__c);
             System.debug('**Settlement_Negotiation_Status_Count__c***'+testCase[0].Settlement_Negotiation_Status_Count__c);
             System.debug('***Total_Loss_Item_Count__c**'+testCase[0].Total_Loss_Item_Count__c);
             System.debug('***Merit_Settled_Count__c**'+testCase[0].Merit_Settled_Count__c);
             System.debug('**Merit_Negotiation_Count__c***'+testCase[0].Merit_Negotiation_Count__c);
             System.debug('**Merit_Arbitration_Count__c***'+testCase[0].Merit_Arbitration_Count__c);
             System.debug('***Merit_Arbitrated_Count_**'+testCase[0].Merit_Arbitrated_Count__c);
             System.debug('**Arbitration_Negotiation_Count__c***'+testCase[0].Arbitration_Negotiation_Count__c);
             System.debug('**Arbitration_Completed_Count__c***'+testCase[0].Arbitration_Completed_Count__c);
             System.debug('**Protocol***'+testCase[0].Protocol__r.Name);
             */
             
             update testCase; 
    
    test.stoptest();
    

}



}