force-app/main/default/objects/Case/fields/Arbitration_Accept_Date__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Accept_Date__c</fullName>
    <label>Arbitration Accept Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitration_Firm__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arbitration Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Arbitration Firm)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitrator_Accept_Decline__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Accept_Decline__c</fullName>
    <inlineHelpText>Arbitrator responds to invitation to arbitrate case</inlineHelpText>
    <label>Arbitrator Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitrator_Contact__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arbitrator Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Arbitration_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Arbitrator Contact)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitrator_Email__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Email__c</fullName>
    <label>Arbitrator Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invite_Arbitrator__c.field-meta.xml
<CustomField>
    <fullName>Invite_Arbitrator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invite Arbitrator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loss_Category__c/Loss_Category__c.object-meta.xml
<CustomObject>
    <label>Head of Loss</label>
    <nameField>
        <displayFormat>HL {00000}</displayFormat>
        <label>Head of Loss No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Head of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loss_Category__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Head_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loss_Category__c/fields/Schedule_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Schedule_of_Losses__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule of Losses</label>
    <referenceTo>Schedule_of_Losses__c</referenceTo>
    <relationshipName>Loss_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/Loss_Sub_Categories__c.object-meta.xml
<CustomObject>
    <label>Loss Item</label>
    <nameField>
        <displayFormat>Loss Item {0000000}</displayFormat>
        <label>Loss Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loss Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Arbitrated_by__c.field-meta.xml
<CustomField>
    <fullName>Arbitrated_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arbitrated by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loss_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Arbitration_Accepted_Status__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Accepted_Status__c</fullName>
    <label>Arbitration Accepted Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Arbitration_Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Referred_By__c</fullName>
    <label>Arbitration Referred By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Claimant Handler</fullName>
            </value>
            <value>
                <fullName>Defendant Handler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Arbitrator_Rationale__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Rationale__c</fullName>
    <label>Arbitrator Rationale</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Loss_Sub_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Claimant_Final_Offer_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Final_Offer_Confirmed__c</fullName>
    <formula>Loss_Category__r.Case__r.Confirm_Final_Offer_Claimant__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Claimant Final Offer Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Past_Future_Financial_Item__c.field-meta.xml
<CustomField>
    <fullName>Past_Future_Financial_Item__c</fullName>
    <formula>Past_Future_Financial_Losses__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Past/Future Financial Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Referred to Arbitration</fullName>
            </value>
            <value>
                <fullName>Arbitration Doc Prep</fullName>
            </value>
            <value>
                <fullName>Arbitration Final Offers</fullName>
            </value>
            <value>
                <fullName>Arbitrating</fullName>
            </value>
            <value>
                <fullName>Arbitrated</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/Schedule_of_Losses__c.object-meta.xml
<CustomObject>
    <label>Schedule of Losses</label>
    <nameField>
        <displayFormat>Sched {00000}</displayFormat>
        <label>Schedule of Losses No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Arbitration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Start_Date__c</fullName>
    <label>Arbitration Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Arbitrator_Invite_Date__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Invite_Date__c</fullName>
    <label>Arbitrator Invite Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Arbitrators_Award_Finalised__c.field-meta.xml
<CustomField>
    <fullName>Arbitrators_Award_Finalised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Arbitrators Award Finalised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Bilateral_referral_date_passed__c.field-meta.xml
<CustomField>
    <fullName>Bilateral_referral_date_passed__c</fullName>
    <formula>If(
AND(Case__r.Protocol__r.Bilateral_referral_days__c=0,Bilateral_referral_date__c  &lt;= Today()),true,
If(
OR(Bilateral_referral_date__c  &gt;= Today(),ISNULL(Bilateral_referral_date__c ) ),
false,true))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bilateral referral date passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Schedule of Losses</relationshipLabel>
    <relationshipName>Schedule_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimaint_Arbitration_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Claimaint_Arbitration_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimaint Arbitration Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimant_Accept_Decline__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Accept_Decline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimant Accept/Decline</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimant_Confirm_Documents_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Confirm_Documents_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimant Confirm Documents Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimant_Final_Offer_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Final_Offer_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimant Final Offer Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Accept_Decline__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Accept_Decline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Accept/Decline</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Arbitration_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Arbitration_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Arbitration Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Confirm_Documents_uploaded__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Confirm_Documents_uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Confirm Documents uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Final_Offer_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Final_Offer_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Final Offer Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Doc_Prep_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Doc_Prep_Start_Date__c</fullName>
    <label>Doc Prep Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Final_Offers_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Offers_Start_Date__c</fullName>
    <label>Final Offers Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Invite_Arbitrator__c.field-meta.xml
<CustomField>
    <fullName>Invite_Arbitrator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invite Arbitrator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/No_referral_date_passed__c.field-meta.xml
<CustomField>
    <fullName>No_referral_date_passed__c</fullName>
    <formula>If(OR(No_referral_date__c &gt; Today(),ISNULL(No_referral_date__c) ),false,true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No referral (date) passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Unilateral_Arbitration_Overlap__c.field-meta.xml
<CustomField>
    <fullName>Unilateral_Arbitration_Overlap__c</fullName>
    <formula>If(AND(Unilateral_referral_date_passed__c=True,Unilateral_referral_date__c&gt;= Doc_Prep_Start_Date__c),True,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unilateral Arbitration Overlap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Unilateral_referral_date_passed__c.field-meta.xml
<CustomField>
    <fullName>Unilateral_referral_date_passed__c</fullName>
    <formula>If(
AND(
Case__r.Protocol__r.Unilateral_referral_days__c =0,Unilateral_referral_date__c  &lt;= Today()),true,
If(OR(Unilateral_referral_date__c  &gt;= Today(),ISNULL(Unilateral_referral_date__c) ),
false,true))</formula>
    <label>Unilateral referral date passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SOLHandler.cls
Public Class SOLHandler{



Public static void ResetArbitration(Set<String> set_Case){


         List<Schedule_of_Losses__c> ScheduleofLosses = new List<Schedule_of_Losses__c>([Select id, Bilateral_referral_date_passed__c,No_referral_date_passed__c,Unilateral_referral_date_passed__c,
         Claimant_Accept_Decline__c, Defendant_Accept_Decline__c,Arbitrators_Award_Finalised__c,  Claimant_Final_Offer_Confirmed__c,Defendant_Final_Offer_Confirmed__c,Claimant_Confirm_Documents_Uploaded__c, 
         Defendant_Confirm_Documents_uploaded__c,Arbitrator_Invite_Date__c,Invite_Arbitrator__c,   Arbitration_Start_Date__c,Doc_Prep_Start_Date__c,Final_Offers_Start_Date__c,Name,Case__c,Defendant_Arbitration_Submitted__c,Claimaint_Arbitration_Submitted__c From Schedule_of_Losses__c Where Case__c in: set_Case AND (Unilateral_referral_date_passed__c=:false OR (Unilateral_Arbitration_Overlap__c=:True AND Unilateral_referral_date_passed__c=:true)) AND Arbitrators_Award_Finalised__c=:true]);
         
         Set<String> Set_CaseSOL = new Set<String>();
         
         for(Schedule_of_Losses__c sched:ScheduleofLosses){
             
             sched.Claimant_Final_Offer_Confirmed__c =false;
             sched.Defendant_Final_Offer_Confirmed__c=false;
             sched.Claimant_Confirm_Documents_Uploaded__c=false;
             sched.Defendant_Confirm_Documents_uploaded__c=false;
             sched.Defendant_Arbitration_Submitted__c=false;
             sched.Claimaint_Arbitration_Submitted__c=false;
             sched.Arbitrators_Award_Finalised__c = false;
             sched.Arbitration_Start_Date__c=null;
             sched.Doc_Prep_Start_Date__c = null;
             sched.Final_Offers_Start_Date__c = null;
             sched.Arbitrator_Invite_Date__c= null;
             sched.Invite_Arbitrator__c= false;
             
             Set_CaseSOL.add(sched.Case__c);
         }
         update  ScheduleofLosses;

         List<Case> lst_Case = new List<Case>([Select Arbitrator_Email__c,Arbitration_Accept_Date__c,Arbitration_Firm__c,Arbitrator_Contact__c,Arbitrator_Accept_Decline__c,Invite_Arbitrator__c From Case where id in: Set_CaseSOL]);
        
        Set<String> Set_CaseId = new Set<String>();
        Set<String> Set_Con = new Set<String>();
        Set<String> UserId = new Set<String>();
        
        
        
        for(Case cs:lst_Case){ 
             cs.Arbitration_Firm__c=null;
             cs.Arbitration_Accept_Date__c=null;
             cs.Arbitrator_Accept_Decline__c = null;
             cs.Invite_Arbitrator__c = false;
             cs.Arbitrator_Email__c = null;
             Set_CaseId.Add(cs.id);
             Set_Con.Add(cs.Arbitrator_Contact__c);
             cs.Arbitrator_Contact__c=null;
        }
        update lst_Case; 
        system.debug('***UserId**');
        
        User[] ArbUser = [Select id From User where ContactId in: Set_Con];
        
        for(User us:ArbUser){
            UserId.Add(us.id);
        }
        
        system.debug('***UserId**'+UserId+'**Set_CaseId**'+Set_CaseId+'***Set_CaseSOL**'+Set_CaseSOL+'**Sched**'+ScheduleofLosses);
        CaseMemberHandler.RemoverCaseTeamRole('Arbitrator', Set_CaseId, UserId);
        if(Set_CaseSOL.size()>0){
            resetDeclinedItems(Set_CaseSOL);
        }    
}


Public static void resetDeclinedItems(Set<String> Set_CaseSOL ){

        List<Loss_Sub_Categories__c> LossSubCategories;
         LossSubCategories = new List<Loss_Sub_Categories__c>([SELECT Id,Arbitrated_by__c,Loss_Type__c,Arbitrator_Rationale__c,Arbitration_Referred_By__c,Arbitration_Accepted_Status__c,Past_Future_Financial_Item__c, Sub_Category__c,Defendant_Position__c,Loss_Category__c,Sum_Defendent_Position__c,Stage__c,Status__c,Claimant_Position__c,Arbitrator_Award__c,Name,Past_Future_Financial_Losses__r.Name,RecordType.DeveloperName FROM Loss_Sub_Categories__c WHERE Arbitration_Referred_By__c !=:null AND Arbitration_Accepted_Status__c =:'Declined' AND Loss_Category__r.Case__c in:Set_CaseSOL AND Arbitrated_by__c=:null]);
                 
        
        for(Loss_Sub_Categories__c l:LossSubCategories){
            l.Arbitration_Referred_By__c=''; 
            l.Arbitration_Accepted_Status__c ='';    
        }
        
        update LossSubCategories;

}


}