force-app/main/default/objects/Case/fields/Case_Source__c.field-meta.xml
<CustomField>
    <fullName>Case_Source__c</fullName>
    <label>Case Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/ClaimantFirm__c.field-meta.xml
<CustomField>
    <fullName>ClaimantFirm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Claimant Firm)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Defendant Firm</inlineHelpText>
    <label>Defendant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Defendant Firm)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defendant_Firm__c/Defendant_Firm__c.object-meta.xml
<CustomObject>
    <label>Defendant Firm</label>
    <nameField>
        <displayFormat>Defendant Firm - {00000}</displayFormat>
        <label>Defendant Firm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defendant Firms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseHandler.cls
Public Class CaseHandler{
    
    
   // Public Case NewCase {get;set;}
    
    public CaseHandler(ApexPages.StandardController stdController) {
       
       // NewCase = (Case)stdController.getRecord();
        
    }




public CaseHandler(){

    
}





@invocablemethod
Public static void AddUserfirm(List<id> CaseId){
    
  String LOGGEDINUSER;
   for(Id c:CaseId){
    LOGGEDINUSER = UserAccessRights.ProfileName(c);
   }
   
   if(LOGGEDINUSER !='System Administrator'){
               Id ContactId = UserAccessRights.returnContact();
               
               system.debug('*****'+ContactId+'**Logged***'+LOGGEDINUSER);
               Contact[] FirmContact = [Select AccountId from Contact where id=:ContactId];
               
               Case[] CurrentCase = [Select ClaimantFirm__c,Defendant_Firm__c,Case_Source__c From Case Where Id=:CaseId];
               
               if(CurrentCase[0].Case_Source__c=='Claimant'){ //&& LOGGEDINUSER=='Defendant Handler'
                   system.debug('**HUH?***'+FirmContact[0].AccountId);
                   CurrentCase[0].ClaimantFirm__c = FirmContact[0].AccountId;
               }
               else if(CurrentCase[0].Case_Source__c=='Defendant' ){ //&& LOGGEDINUSER=='Defendant Handler'
                   system.debug('**HUH?***'+FirmContact[0].AccountId);
                   CurrentCase[0].Defendant_Firm__c = FirmContact[0].AccountId;
               } 
               if(CurrentCase[0].id !=null){
                   system.debug('**Update***'+CurrentCase[0].id);
                   Update CurrentCase;
               } 
    }           
}




}