force-app/main/default/objects/Case/fields/Claimant_Information__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Information</label>
    <referenceTo>Claimant_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Information__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Defendant Information</label>
    <referenceTo>Defendant_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Incident_Information__c.field-meta.xml
<CustomField>
    <fullName>Incident_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incident Information</label>
    <referenceTo>Incident_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Personal_Injury_Public_Liability_End_to_End.recordType-meta.xml
<RecordType>
    <fullName>Personal_Injury_Public_Liability_End_to_End</fullName>
    <active>true</active>
    <businessProcess>Process 1</businessProcess>
    <label>Personal Injury - Public Liability - End-to-End</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/PersonalInjuryMotorVehicleArbitrationOnly.recordType-meta.xml
<RecordType>
    <fullName>PersonalInjuryMotorVehicleArbitrationOnly</fullName>
    <active>true</active>
    <businessProcess>Support Process Arbitration</businessProcess>
    <description>Case Type 2</description>
    <label>Personal Injury - Motor Vehicle - Arbitration Only</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/PersonalInjuryMotorVehicleEndtoEnd_1.recordType-meta.xml
<RecordType>
    <fullName>PersonalInjuryMotorVehicleEndtoEnd_1</fullName>
    <active>true</active>
    <businessProcess>Process 1</businessProcess>
    <description>Case Type 1</description>
    <label>Personal Injury - Motor Vehicle - End-to-End</label>
</RecordType>

force-app/main/default/objects/Claimant_Information__c/Claimant_Information__c.object-meta.xml
<CustomObject>
    <label>Claimant Information</label>
    <nameField>
        <displayFormat>Claimant - {000000}</displayFormat>
        <label>Claimant Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claimant Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claimant_Information__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claimant Information</relationshipLabel>
    <relationshipName>Claimant_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claimant_Information__c/fields/Schedule_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Schedule_of_Losses__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule of Losses</label>
    <referenceTo>Schedule_of_Losses__c</referenceTo>
    <relationshipLabel>Claimant Information</relationshipLabel>
    <relationshipName>Claimant_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claimant_Information__c/recordTypes/Arbitration_Only.recordType-meta.xml
<RecordType>
    <fullName>Arbitration_Only</fullName>
    <active>true</active>
    <label>Arbitration Only</label>
</RecordType>

force-app/main/default/objects/Claimant_Information__c/recordTypes/Claimant_PI_EL_EE.recordType-meta.xml
<RecordType>
    <fullName>Claimant_PI_EL_EE</fullName>
    <active>true</active>
    <label>Claimant - PI-EL-EE</label>
</RecordType>

force-app/main/default/objects/Claimant_Information__c/recordTypes/Claimant_PI_PL_EE.recordType-meta.xml
<RecordType>
    <fullName>Claimant_PI_PL_EE</fullName>
    <active>true</active>
    <label>Claimant - PI-PL-EE</label>
</RecordType>

force-app/main/default/objects/Defendant_Information__c/Defendant_Information__c.object-meta.xml
<CustomObject>
    <label>Defendant Information</label>
    <nameField>
        <displayFormat>Defendant - {000000}</displayFormat>
        <label>Defendant Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defendant Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Defendant_Information__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Defendant Information</relationshipLabel>
    <relationshipName>Defendant_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Defendant_Information__c/recordTypes/Defendant_PI_EL_EE.recordType-meta.xml
<RecordType>
    <fullName>Defendant_PI_EL_EE</fullName>
    <active>true</active>
    <label>Defendant - PI-EL-EE</label>
</RecordType>

force-app/main/default/objects/Defendant_Information__c/recordTypes/Defendant_PI_PL_EE.recordType-meta.xml
<RecordType>
    <fullName>Defendant_PI_PL_EE</fullName>
    <active>true</active>
    <label>Defendant - PI-PL-EE</label>
</RecordType>

force-app/main/default/objects/Defendant_Information__c/recordTypes/End_to_End.recordType-meta.xml
<RecordType>
    <fullName>End_to_End</fullName>
    <active>true</active>
    <label>End to End</label>
</RecordType>

force-app/main/default/objects/Incident_Information__c/Incident_Information__c.object-meta.xml
<CustomObject>
    <label>Incident Information</label>
    <nameField>
        <displayFormat>Incident - {000000}</displayFormat>
        <label>Incident Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incident_Information__c/recordTypes/Arbitration_Only.recordType-meta.xml
<RecordType>
    <fullName>Arbitration_Only</fullName>
    <active>true</active>
    <label>Arbitration Only</label>
</RecordType>

force-app/main/default/objects/Incident_Information__c/recordTypes/End_to_End.recordType-meta.xml
<RecordType>
    <fullName>End_to_End</fullName>
    <active>true</active>
    <label>PI-MV-End to End</label>
</RecordType>

force-app/main/default/objects/Incident_Information__c/recordTypes/PI_EL_End_to_End.recordType-meta.xml
<RecordType>
    <fullName>PI_EL_End_to_End</fullName>
    <active>true</active>
    <label>PI-EL-End to End</label>
</RecordType>

force-app/main/default/objects/Incident_Information__c/recordTypes/PI_PL_End_to_End.recordType-meta.xml
<RecordType>
    <fullName>PI_PL_End_to_End</fullName>
    <active>true</active>
    <label>PI-PL-End to End</label>
</RecordType>

force-app/main/default/objects/Loss_Category__c/Loss_Category__c.object-meta.xml
<CustomObject>
    <label>Head of Loss</label>
    <nameField>
        <displayFormat>HL {00000}</displayFormat>
        <label>Head of Loss No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Head of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loss_Category__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Head_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loss_Category__c/fields/Loss_Category_Types__c.field-meta.xml
<CustomField>
    <fullName>Loss_Category_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loss Category Types</label>
    <referenceTo>Loss_Category_Types__c</referenceTo>
    <relationshipName>Loss_Categoryies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loss_Category__c/fields/Schedule_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Schedule_of_Losses__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule of Losses</label>
    <referenceTo>Schedule_of_Losses__c</referenceTo>
    <relationshipName>Loss_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loss_Category__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Loss_Category__c/recordTypes/Past_or_Future_Losses.recordType-meta.xml
<RecordType>
    <fullName>Past_or_Future_Losses</fullName>
    <active>true</active>
    <description>Past or Future Losses</description>
    <label>Past or Future Losses</label>
</RecordType>

force-app/main/default/objects/Loss_Category__c/recordTypes/Personal_Injury_and_Loss_of_Amenity.recordType-meta.xml
<RecordType>
    <fullName>Personal_Injury_and_Loss_of_Amenity</fullName>
    <active>true</active>
    <label>Personal Injury and Loss of Amenity</label>
</RecordType>

force-app/main/default/objects/Loss_Category_Types__c/Loss_Category_Types__c.object-meta.xml
<CustomObject>
    <label>Loss Category Type</label>
    <nameField>
        <label>Loss Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loss Category Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Merit__c/Merit__c.object-meta.xml
<CustomObject>
    <label>Merit</label>
    <nameField>
        <label>Merit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merit__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Merits</relationshipLabel>
    <relationshipName>Merits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Schedule_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Schedule_of_Losses__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule of Losses</label>
    <referenceTo>Schedule_of_Losses__c</referenceTo>
    <relationshipLabel>Merits</relationshipLabel>
    <relationshipName>Merits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocol_Option__c/Protocol_Option__c.object-meta.xml
<CustomObject>
    <label>Protocol Option</label>
    <nameField>
        <displayFormat>PO - {000000}</displayFormat>
        <label>Protocol Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protocol Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Protocol_Option__c/fields/Protocol_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Item_Type__c</fullName>
    <label>Protocol Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Protocol_Option__c/fields/Protocol_Option__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Option__c</fullName>
    <label>Protocol Option</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Protocol_Item_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incident - PI-MV-EE</fullName>
            </value>
            <value>
                <fullName>Incident - PI-MV-AO</fullName>
            </value>
            <value>
                <fullName>Incident - PI-EL-EE</fullName>
            </value>
            <value>
                <fullName>Incident - PI-PL-EE</fullName>
            </value>
            <value>
                <fullName>Claimant - PI-MV-EE</fullName>
            </value>
            <value>
                <fullName>Claimant - PI-MV-AO</fullName>
            </value>
            <value>
                <fullName>Claimant - PI-EL-EE</fullName>
            </value>
            <value>
                <fullName>Claimant - PI-PL-EE</fullName>
            </value>
            <value>
                <fullName>Defendant - PI-MV-EE</fullName>
            </value>
            <value>
                <fullName>Defendant - PI-MV-AO</fullName>
            </value>
            <value>
                <fullName>Defendant - PI-EL-EE</fullName>
            </value>
            <value>
                <fullName>Defendant - PI-PL-EE</fullName>
            </value>
            <value>
                <fullName>Case - PI-MV-EE</fullName>
            </value>
            <value>
                <fullName>Case - PI-MV-AO</fullName>
            </value>
            <value>
                <fullName>Case - PI-EL-EE</fullName>
            </value>
            <value>
                <fullName>Case - PI-PL-EE</fullName>
            </value>
            <value>
                <fullName>Case Arbribtration</fullName>
                <isActive>false</isActive>
                <label>Case Arbribtration</label>
            </value>
            <value>
                <fullName>Case EndtoEnd</fullName>
                <isActive>false</isActive>
                <label>Case EndtoEnd</label>
            </value>
            <value>
                <fullName>Claimant Arbitration</fullName>
                <isActive>false</isActive>
                <label>Claimant Arbitration</label>
            </value>
            <value>
                <fullName>Claimant EndtoEnd</fullName>
                <isActive>false</isActive>
                <label>Claimant EndtoEnd</label>
            </value>
            <value>
                <fullName>Defendant Arbitration</fullName>
                <isActive>false</isActive>
                <label>Defendant Arbitration</label>
            </value>
            <value>
                <fullName>Defendant EndtoEnd</fullName>
                <isActive>false</isActive>
                <label>Defendant EndtoEnd</label>
            </value>
            <value>
                <fullName>Incident Arbitration</fullName>
                <isActive>false</isActive>
                <label>Incident Arbitration</label>
            </value>
            <value>
                <fullName>Incident EndtoEnd</fullName>
                <isActive>false</isActive>
                <label>Incident EndtoEnd</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Protocol_Option__c/fields/Record_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_ID__c</fullName>
    <label>Record Type ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/Schedule_of_Losses__c.object-meta.xml
<CustomObject>
    <label>Schedule of Losses</label>
    <nameField>
        <displayFormat>Sched {00000}</displayFormat>
        <label>Schedule of Losses No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Schedule of Losses</relationshipLabel>
    <relationshipName>Schedule_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimant_Information__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Information</label>
    <referenceTo>Claimant_Information__c</referenceTo>
    <relationshipLabel>Schedule of Losses</relationshipLabel>
    <relationshipName>Schedule_of_Losses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProtocolSetup.cls
Public Class ProtocolSetup{

@invocablemethod
Public static void SetProtocolOptionRecordType(List<Id> optionsId){
    
    system.debug('**IN**');
    List<Protocol_Option__c> lst_Options = new List<Protocol_Option__c>([Select id,Protocol_Option__c,Record_Type_ID__c,Protocol_Item_Type__c from Protocol_Option__c where id in:optionsId  ]);
    PopulateProtocolOptions(lst_Options);
}



Public Static void PopulateProtocolOptions(List<Protocol_Option__c> lst_Options){

    
    List<RecordType> lst_recordIncident = new List<RecordType>([Select Id,DeveloperName from RecordType Where SobjectType=:'Incident_Information__c']);    
    List<RecordType> lst_recordClaim = new List<RecordType>([Select Id,DeveloperName from RecordType Where SobjectType=:'Claimant_Information__c']);    
    List<RecordType> lst_recordDef = new List<RecordType>([Select Id,DeveloperName from RecordType Where SobjectType=:'Defendant_Information__c']);    
    List<RecordType> lst_recordCase = new List<RecordType>([Select Id,DeveloperName from RecordType Where SobjectType=:'Case']);    
    
    system.debug('**ONE**'+lst_recordClaim);
    
    
    Map<String,String> Map_RecordInc = new Map<String,String>();
    Map<String,String> Map_RecordClaim = new Map<String,String>();
    Map<String,String> Map_RecordDef = new Map<String,String>();
    Map<String,String> Map_RecordCase = new Map<String,String>();
    
   
    
   
    
    for(RecordType rt:lst_recordIncident){
       
       if(rt.DeveloperName=='Arbitration_Only'){ 
            Map_RecordInc.put('Arb',rt.id);
       }
       else if(rt.DeveloperName=='PI_EL_End_to_End'){  
            Map_RecordInc.put('PIEL',rt.id);
       }
       else if(rt.DeveloperName=='End_to_End'){  
            Map_RecordInc.put('End',rt.id);
       }
       else if(rt.DeveloperName=='PI_PL_End_to_End'){ 
            Map_RecordInc.put('PIPL',rt.id);
       }
    }
    
    for(RecordType rt:lst_recordClaim){
       system.debug('**DeveloperName**'+rt.DeveloperName);
      if(rt.DeveloperName=='Arbitration_Only'){ 
            Map_RecordClaim.put('Arb',rt.id);
            
            system.debug('**Claim**'+Map_RecordClaim.get('Arb')+'****'+rt.id);
       }
       else if(rt.DeveloperName=='Claimant_PI_EL_EE'){   
            Map_RecordClaim.put('PIEL',rt.id);
       }
       else if(rt.DeveloperName=='Claimant_PI_PL_EE'){   
            Map_RecordClaim.put('PIPL',rt.id);
       }
       else if(rt.DeveloperName=='End_to_End'){ 
            Map_RecordClaim.put('End',rt.id);
       } 
    }
    
    for(RecordType rt:lst_recordDef){
       
       if(rt.DeveloperName=='Arbitration_Only'){ 
            Map_RecordDef.put('Arb',rt.id);
       }
       else if(rt.DeveloperName=='Defendant_PI_EL_EE'){   
            Map_RecordDef.put('PIEL',rt.id);
       }
       else if(rt.DeveloperName=='Defendant_PI_PL_EE'){   
            Map_RecordDef.put('PIPL',rt.id);
       }
       else if(rt.DeveloperName=='End_to_End'){ 
            Map_RecordDef.put('End',rt.id);
       } 
    }
    
    for(RecordType rt:lst_recordCase){
       
       if(rt.DeveloperName=='Personal_Injury_Public_Liability_End_to_End'){ 
            Map_RecordCase.put('PIEL',rt.id);
       }
       else if(rt.DeveloperName=='Personal_Injury_Public_Liability_End_to_End'){ 
            Map_RecordCase.put('PIPL',rt.id);
       }
       else if(rt.DeveloperName=='PersonalInjuryMotorVehicleArbitrationOnly'){ 
            Map_RecordCase.put('Arb',rt.id);
       }
       else if(rt.DeveloperName=='PersonalInjuryMotorVehicleEndtoEnd_1'){ 
            Map_RecordCase.put('End',rt.id);
       }
    }
    
    for( Protocol_Option__c  o:lst_Options){
        
        if(o.Protocol_Item_Type__c =='Claimant'){
        system.debug('**TWO**');
                if(o.Protocol_Option__c=='Claimant - PI-MV-AO'){ 
                  o.Record_Type_ID__c =  Map_RecordClaim.get('Arb');
                  system.debug('**Record**'+Map_RecordClaim.get('Arb'));
               }
               else if(o.Protocol_Option__c=='Claimant - PI-EL-EE'){   
                   o.Record_Type_ID__c = Map_RecordClaim.get('PIEL');
               }
               else if(o.Protocol_Option__c=='Claimant - PI-PL-EE'){   
                   o.Record_Type_ID__c = Map_RecordClaim.get('PIPL');
               }
               else if(o.Protocol_Option__c=='Claimant - PI-MV-EE'){ 
                  o.Record_Type_ID__c =  Map_RecordClaim.get('End');
               } 
        }
        else if(o.Protocol_Item_Type__c=='Defendant'){
                
                
                if(o.Protocol_Option__c=='Defendant - PI-MV-AO'){ 
                   o.Record_Type_ID__c = Map_RecordDef.get('Arb');
               }
               else if(o.Protocol_Option__c=='Defendant - PI-EL-EE'){   
                   o.Record_Type_ID__c = Map_RecordDef.get('PIEL');
               }
               else if(o.Protocol_Option__c=='Defendant - PI-PL-EE'){   
                   o.Record_Type_ID__c = Map_RecordDef.get('PIPL');
               }
               else if(o.Protocol_Option__c=='Defendant - PI-MV-EE'){ 
                   o.Record_Type_ID__c = Map_RecordDef.get('End');
               } 
               
               system.debug('**DEFN**'+o.Record_Type_ID__c);
        }
        else if(o.Protocol_Item_Type__c=='Case'){
            if(o.Protocol_Option__c=='Case - PI-MV-AO'){ 
                    o.Record_Type_ID__c =Map_RecordCase.get('Arb');
               }
               else if(o.Protocol_Option__c=='Case - PI-EL-EE'){   
                   o.Record_Type_ID__c = Map_RecordCase.get('PIEL');
               }
               else if(o.Protocol_Option__c=='Case - PI-PL-EE'){   
                   o.Record_Type_ID__c = Map_RecordCase.get('PIPL');
               }
               else if(o.Protocol_Option__c=='Case - PI-MV-EE'){ 
                  o.Record_Type_ID__c =  Map_RecordCase.get('End');
               } 
        }
        else if(o.Protocol_Item_Type__c=='Incident'){
                if(o.Protocol_Option__c=='Incident - PI-MV-AO'){ 
                   o.Record_Type_ID__c = Map_RecordInc.get('Arb');
               }
               else if(o.Protocol_Option__c=='Incident - PI-EL-EE'){   
                  o.Record_Type_ID__c =  Map_RecordInc.get('PIEL');
               }
               else if(o.Protocol_Option__c=='Incident - PI-PL-EE'){   
                  o.Record_Type_ID__c =  Map_RecordInc.get('PIPL');
               }
               else if(o.Protocol_Option__c=='Incident - PI-MV-EE'){ 
                   o.Record_Type_ID__c = Map_RecordInc.get('End');
               } 
        }
        
        system.debug('**Opp**'+o.Protocol_Item_Type__c+'**Rec**'+o.Record_Type_ID__c);
    }
    
   //update lst_Options; 
    
  system.debug('**DEFN22**'+lst_Options);

}










/*
Public void AddHeadsofLosstoCase(String CaseID){
   
   
    List<RecordType> lst_recordType = new List<RecordType>([Select Id,DeveloperName from RecordType Where SobjectType=:'Loss_Category__c']);    
    
    
    Map<String,String> Map_RecordTypes = new Map<String,String>();
    
    for(RecordType rt:lst_recordType){
       
       if(rt.DeveloperName=='Past_or_Future_Losses'){ 
            Map_RecordTypes.put('Loss',rt.id);
       }
       else if(rt.DeveloperName=='Personal_Injury_and_Loss_of_Amenity'){ 
            Map_RecordTypes.put('PSLA',rt.id);
       }
       else{ 
            Map_RecordTypes.put('Other',rt.id);
       } 
    }
    
    List<Loss_Category__c> lst_headofLoss = new List<Loss_Category__c>();
    
    Schedule_of_Losses__c ScheduleLosses = new Schedule_of_Losses__c();
    
    ScheduleLosses.Case__c = CaseID;
    Insert ScheduleLosses;
    
    Loss_Category_Types__c[] LossTypes = [Select id,Name from Loss_Category_Types__c];
    
    
    for(Loss_Category_Types__c t:LossTypes){
        
        Loss_Category__c loss = new Loss_Category__c();
        loss.Case__c = CaseID;
        loss.Schedule_of_Losses__c = ScheduleLosses.id;
        loss.Loss_Category_Types__c = t.id;
        
        if(t.Name == 'Future Financial Losses' || t.Name == 'Past Financial Losses'){
            loss.RecordTypeId = Map_RecordTypes.get('Loss');
        }
        else if(t.Name == 'Personal Injury and Loss of Amenity'){
            loss.RecordTypeId = Map_RecordTypes.get('PSLA');
        }
        else{
            loss.RecordTypeId = Map_RecordTypes.get('Other');
        }  
       lst_headofLoss.add(loss); 
              
    }
    
    
    Insert lst_headofLoss;
    
    Merit__c Merit = new Merit__c();
    Merit.Schedule_of_Losses__c = ScheduleLosses.id;
    Merit.Related_Case__c = CaseID;
    Insert Merit;



}
*/











}