force-app/main/default/objects/Case/fields/Claimant_Position__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Position__c</fullName>
    <label>Claimant Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loss_Category__c/Loss_Category__c.object-meta.xml
<CustomObject>
    <label>Head of Loss</label>
    <nameField>
        <displayFormat>HL {00000}</displayFormat>
        <label>Head of Loss No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Head of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loss_Category__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Head_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loss_Category__c/fields/Head_of_Loss_Type__c.field-meta.xml
<CustomField>
    <fullName>Head_of_Loss_Type__c</fullName>
    <label>Head of Loss Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bereavement</fullName>
            </value>
            <value>
                <fullName>Disadvantage on Labour Market</fullName>
            </value>
            <value>
                <fullName>Future Financial Losses</fullName>
            </value>
            <value>
                <fullName>Legal Costs</fullName>
            </value>
            <value>
                <fullName>Loss of Congenial Employment</fullName>
            </value>
            <value>
                <fullName>Past Financial Losses</fullName>
            </value>
            <value>
                <fullName>Pain, Suffering &amp; Loss of Amenities</fullName>
            </value>
            <value>
                <fullName>Total Loss Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loss_Category__c/fields/Schedule_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Schedule_of_Losses__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule of Losses</label>
    <referenceTo>Schedule_of_Losses__c</referenceTo>
    <relationshipName>Loss_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loss_Category__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Merit__c/Merit__c.object-meta.xml
<CustomObject>
    <label>Merit</label>
    <nameField>
        <label>Merit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merit__c/fields/Arbitration_Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Referred_By__c</fullName>
    <label>Arbitration Referred By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Claimant Handler</fullName>
            </value>
            <value>
                <fullName>Defendant Handler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Arbitrator_Award__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Award__c</fullName>
    <label>Arbitrator Award</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Claimant_Position__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Position__c</fullName>
    <label>Claimant Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Defendant_Position__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Position__c</fullName>
    <label>Defendant Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Merits</relationshipLabel>
    <relationshipName>Merits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Schedule_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Schedule_of_Losses__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule of Losses</label>
    <referenceTo>Schedule_of_Losses__c</referenceTo>
    <relationshipLabel>Merits</relationshipLabel>
    <relationshipName>Merits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negotiating</fullName>
                <default>true</default>
                <label>Negotiating</label>
            </value>
            <value>
                <fullName>Referred to Arbitration</fullName>
            </value>
            <value>
                <fullName>Arbitration Doc Prep</fullName>
            </value>
            <value>
                <fullName>Arbitrating</fullName>
            </value>
            <value>
                <fullName>Arbitration Final Offers</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Arbitrated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/Schedule_of_Losses__c.object-meta.xml
<CustomObject>
    <label>Schedule of Losses</label>
    <nameField>
        <displayFormat>Sched {00000}</displayFormat>
        <label>Schedule of Losses No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Schedule of Losses</relationshipLabel>
    <relationshipName>Schedule_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LossItemViewLightningVF_test.cls
@istest

Public class LossItemViewLightningVF_test{


Public static testmethod void LossItemViewLightning1(){

    test.starttest();
         //   Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPSOL1@noemail.com','SOL1');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
            Test_SetUpCaseProtocol_2.testCreateProtocol();
            
            Case cs = [Select id from Case limit 1];
            PageReference lossitem = Page.LossitemsCategories;  
            lossitem .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(lossitem);
            
            
            LossItemViewLightningVF SOL  = new LossItemViewLightningVF();
            SOL.LOGGEDINUSER = 'Defendant Handler';
            
            Loss_Category__c[] LossCategory = [Select id,Case__c,Head_of_Loss_Type__c,Schedule_of_Losses__c,RecordType.DeveloperName from Loss_Category__c where Head_of_Loss_Type__c = 'Past Financial Losses'];
            lossitem .getParameters().put('RecId',LossCategory[0].id);
            SOL.NewItem(); 
            SOL.NewLossItem.Loss_Type__c='Other Losses';
            lossitem .getParameters().put('Amount','500');
            SOL.SaveItem();
            
            
            lossitem .getParameters().put('RecId',SOL.NewLossItem.id);
            SOL.UpdateItem();
            
            SOL.InitateRationale();
            SOL.UpdateRationale();
            
            
            
           
    
    test.stoptest();
    

}

Public static testmethod void LossItemViewLightning2(){

    test.starttest();
        //    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPSOL1@noemail.com','SOL1');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
            Test_SetUpCaseProtocol_2.testCreateProtocol();
            
            Case cs = [Select id from Case limit 1];
            PageReference lossitem = Page.LossitemsCategories;  
            lossitem .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(lossitem);
            
            
            LossItemViewLightningVF SOL  = new LossItemViewLightningVF();
            
            SOL.LOGGEDINUSER = 'Defendant Handler';
            
            Loss_Category__c[] LossCategory = [Select id,Case__c,Head_of_Loss_Type__c,Schedule_of_Losses__c,RecordType.DeveloperName from Loss_Category__c where Head_of_Loss_Type__c = 'Past Financial Losses'];
            lossitem .getParameters().put('RecId',LossCategory[0].id);
            SOL.NewItem(); 
            SOL.NewLossItem.Loss_Type__c='Other Losses';
            lossitem .getParameters().put('Amount','500');
            SOL.SaveItem();
            
            
            lossitem .getParameters().put('RecId',SOL.NewLossItem.id);
            SOL.UpdateItem();
            
            SOL.InitateInterest();
            SOL.StartDate = '2019-10-10';
            SOL.UpdateInterest();
            SOL.RemoveInterest();
            
           
    
    test.stoptest();
    

}



Public static testmethod void LossItemViewLightning3(){

    test.starttest();
        //    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPSOL1@noemail.com','SOL1');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
            Test_SetUpCaseProtocol_2.testCreateProtocol();
            
            Case cs = [Select id from Case limit 1];
            PageReference lossitem = Page.LossitemsCategories;  
            lossitem .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(lossitem);
            
            
            LossItemViewLightningVF SOL  = new LossItemViewLightningVF();
            SOL.LOGGEDINUSER = 'Defendant Handler';
            
            Loss_Category__c[] LossCategory = [Select id,Case__c,Head_of_Loss_Type__c,Schedule_of_Losses__c,RecordType.DeveloperName from Loss_Category__c where Head_of_Loss_Type__c = 'Past Financial Losses'];
            lossitem .getParameters().put('RecId',LossCategory[0].id);
            SOL.NewItem(); 
            SOL.NewLossItem.Loss_Type__c='Other Losses';
            lossitem .getParameters().put('Amount','500');
            SOL.SaveItem();
           
            
            LossCategory = [Select id,Case__c,Head_of_Loss_Type__c,Schedule_of_Losses__c,RecordType.DeveloperName from Loss_Category__c where Head_of_Loss_Type__c = 'Pain, Suffering & Loss of Amenities'];
            lossitem .getParameters().put('RecId',LossCategory[0].id);
            SOL.NewCode();
            SOL.SaveCode();
            
    
    test.stoptest();
    

}



Public static testmethod void LossItemViewLightning4(){

    test.starttest();
        //    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPSOL2@noemail.com','SOL2');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
            Test_SetUpCaseProtocol_2.testCreateProtocol();
            
            Case cs = [Select id from Case limit 1];
            PageReference lossitem = Page.LossitemsCategories;  
            lossitem .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(lossitem);
            
            
            LossItemViewLightningVF SOL  = new LossItemViewLightningVF();
            SOL.LOGGEDINUSER = 'Defendant Handler';
            
            Loss_Category__c[] LossCategory = [Select id,Case__c,Head_of_Loss_Type__c,Schedule_of_Losses__c,RecordType.DeveloperName from Loss_Category__c where Head_of_Loss_Type__c = 'Past Financial Losses'];
            lossitem .getParameters().put('RecId',LossCategory[0].id);
            SOL.NewItem(); 
            SOL.NewLossItem.Loss_Type__c='Other Losses';
            lossitem .getParameters().put('Amount','500');
            SOL.SaveItem();
            SOL.populateCaseFiles();
            SOL.SaveCaseFilesSelection();
            
            
    
    test.stoptest();
    

}

Public static testmethod void LossItemViewLightning5(){

    test.starttest();
        //    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPSOL3@noemail.com','SOL3');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
            Test_SetUpCaseProtocol_2.testCreateProtocol();
            
            Case cs = [Select id from Case limit 1];
            PageReference lossitem = Page.LossitemsCategories;  
            lossitem .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(lossitem);
            
            
            LossItemViewLightningVF SOL  = new LossItemViewLightningVF();
            SOL.LOGGEDINUSER = 'Defendant Handler';
            
            List<Merit__c> lstMerit = new List<Merit__c>([Select id,Defendant_Position__c,Arbitration_Referred_By__c,Status__c, Arbitrator_Award__c,Related_Case__c, Claimant_Position__c, name, Schedule_of_Losses__c From Merit__c limit 1]);

            
            lossitem .getParameters().put('RecId',lstMerit[0].id);
            lossitem .getParameters().put('MerPerc','90');
           
            SOL.UpdateMerit(); 
      
    test.stoptest();
    

}






}