force-app/main/default/objects/Case/fields/Claimant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__c</field>
            <operation>equals</operation>
            <valueField>$Source.ClaimantFirm__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Defendant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Defendant_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases (Defendant Firm Team)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Comment__c/Case_Comment__c.object-meta.xml
<CustomObject>
    <label>Case Comment (Chat)</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Case Comment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Comment (Chats)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Comment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Comments_Chat</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Comment__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case_Comment__c/fields/Share_with_Arbitrator__c.field-meta.xml
<CustomField>
    <fullName>Share_with_Arbitrator__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Share with Arbitrator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Comment__c/fields/Share_with_Facilitor__c.field-meta.xml
<CustomField>
    <fullName>Share_with_Facilitor__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Share with Facilitator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CaseCommentCaseTeamHandler_test.cls
@istest

Public class CaseCommentCaseTeamHandler_test{


Public static testmethod void CaseCommentCaseTeamHandler1(){

    test.starttest();
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();                                  
            Test_SetUpCaseProtocol_2a.testCreateProtocol();
             
            Case cs = [Select id,Claimant_Firm_Team__c,Defendant_Firm_Team__c from Case limit 1];           
            
            system.debug('**CS TEAM**'+cs.Claimant_Firm_Team__c);
            
            Case_Comment__c Case_Comment = new Case_Comment__c(Case__c = cs.id,Comment__c ='Test',Share_with_Arbitrator__c = true,Share_with_Facilitor__c= true); 
            insert Case_Comment;
            
             User[] user1 = [Select id From User where username='handler4@testINAP.com']; 
    
            CaseTeamMember[] CaseTeamMember = [Select MemberId,TeamRoleId,ParentId From CaseTeamMember ];  
            
            system.debug('**CS CaseTeamMember**'+CaseTeamMember);
            
           List<ID> ids = new List<ID>();
           ids.add(CaseTeamMember[0].id);
           
           CaseCommentCaseTeamHandler.AddCaseCommentSharing(ids);
           
           //Contact[] con = [Select id from Contact where email='handler4@testINAP.com']; 
            
            CaseCommentCaseTeamHandler.RemoveCaseCommentSharing(ids);
            
    test.stoptest();
    

}



}