force-app/main/default/objects/Case/fields/Claimant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__c</field>
            <operation>equals</operation>
            <valueField>$Source.ClaimantFirm__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ClaimantFirm__c.field-meta.xml
<CustomField>
    <fullName>ClaimantFirm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Claimant Firm)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Accept_Reject__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Accept_Reject__c</fullName>
    <label>Defendant Accept/Reject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Agree_to_Arbitration_Process__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Agree_to_Arbitration_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant - Agree to Arbitration Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Defendant Firm</inlineHelpText>
    <label>Defendant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Defendant Firm)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Defendant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Defendant_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases (Defendant Firm Team)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registration</fullName>
                <default>true</default>
                <label>Registration</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Finalize</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Arbitrating</fullName>
                <isActive>false</isActive>
                <label>Arbitrating</label>
            </value>
            <value>
                <fullName>Closed Awarded</fullName>
                <isActive>false</isActive>
                <label>Closed Awarded</label>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defendant_Firm__c/Defendant_Firm__c.object-meta.xml
<CustomObject>
    <label>Defendant Firm</label>
    <nameField>
        <displayFormat>Defendant Firm - {00000}</displayFormat>
        <label>Defendant Firm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defendant Firms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Defendant_Firm__c/fields/Firm__c.field-meta.xml
<CustomField>
    <fullName>Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Defendant Firms</relationshipLabel>
    <relationshipName>Defendant_Firms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defendant_Firm__c/fields/Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firm Team</label>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Defendant Firms</relationshipLabel>
    <relationshipName>Defendant_Firms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Firm_Team__c/Firm_Team__c.object-meta.xml
<CustomObject>
    <label>Firm Team</label>
    <nameField>
        <label>Firm Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firm Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Firm_Team__c/fields/Firm__c.field-meta.xml
<CustomField>
    <fullName>Firm__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Firm Teams</relationshipLabel>
    <relationshipName>Firm_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Batch_CaseReferalHandler_test.cls
@istest

Public class Batch_CaseReferalHandler_test{


Public static testmethod void CaseReferalHandler1(){

    test.starttest();
      Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_SetUpCaseProtocol_1.testCreateProtocol();
           
              TestDateghostDraft.Setup();   
              
            Case cs = [Select id,Stage__c from Case limit 1];
            PageReference QuickActions = Page.QuickActionsCase;  
            QuickActions .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(QuickActions);
            
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            CaseQuickActions Quick  = new CaseQuickActions(sc);
            
            
            Account[] FirmCl = [Select id from Account where Name = 'Legalsmiths'];
            Quick.CaseQuick.ClaimantFirm__c = FirmCl[0].id;
         
        
             Account[] FirmDef = [Select id from Account where Name = 'Insuresmiths'];
             Quick.CaseQuick.Defendant_Firm__c = FirmDef[0].id; 
             Quick.CaseQuick.Subject = 'Test';
                                   
          
            Firm_Team__c[] testCl = [Select Firm__c From Firm_Team__c where Firm__c=:FirmCl[0].id];
            Quick.CaseQuick.Claimant_Firm_Team__c = testCl[0].id;
         
         
            Firm_Team__c[] testDef = [Select Firm__c From Firm_Team__c where Firm__c=:FirmDef[0].id];
            Quick.CaseQuick.Defendant_Firm_Team__c = testDef[0].id;
            Quick.CaseQuick.Defendant_Accept_Reject__c='Accept';
            Quick.CaseQuick.Defendant_Agree_to_Arbitration_Process__c=true;
            
            User[] UOwner = [Select id from User where (Profile.Name = 'System Administrator' OR Profile.Name = 'Market Maker') AND Isactive=:true ];
            Quick.CaseQuick.OwnerId =  UOwner[0].id;
            Quick.CaseQuick.status='Referred';
            Update Quick.CaseQuick;
            
          
            
            Quick.AcceptReject();
            system.debug('**CaseSTage**'+Quick.CaseQuick.Stage__c);
           
            
            
            Batch_CaseReferalHandler updateReferal = new Batch_CaseReferalHandler();
            String sch = '20 35 8 10 2 ?';
            system.schedule('Sequence Job Test Submit Order', sch, updateReferal);
    
    test.stoptest();
    

}



}