force-app/main/default/objects/Case/fields/Claimant_Information__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Information</label>
    <referenceTo>Claimant_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Claimant_Information__c/Claimant_Information__c.object-meta.xml
<CustomObject>
    <label>Claimant Information</label>
    <nameField>
        <displayFormat>Claimant - {000000}</displayFormat>
        <label>Claimant Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claimant Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Claimant_Information__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Claimant Information</relationshipLabel>
    <relationshipName>Claimant_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Claimant_Information__c/fields/Claimant_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Date_of_Birth__c</fullName>
    <label>Claimant Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claimant_Information__c/fields/Claimant_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Last_Name__c</fullName>
    <label>Claimant Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claimant_Information__c/fields/Claimant_Vehicle_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Vehicle_Registration_Number__c</fullName>
    <label>Claimant Vehicle Registration Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Claimant_Information__c/fields/Editable__c.field-meta.xml
<CustomField>
    <fullName>Editable__c</fullName>
    <formula>if(text(Case__r.Status)=&apos;Created&apos;,false,true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Editable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ClaimantRelatedList.cls
public class ClaimantRelatedList {
    
    @AuraEnabled
    public static List<Claimant_Information__c> getClaimantInfo(String caseId) {
        
        List<Claimant_Information__c> claimantInfo = [SELECT Id, 
                                                      Name,
                                                      Case__c,
                                                      Case__r.Status,
                                                      Claimant_First_Name__c,
                                                      Claimant_Last_Name__c,
                                                      Editable__c,
                                                      Claimant_Vehicle_Registration_Number__c,
                                                      Claimant_Date_of_Birth__c
                                                      FROM Claimant_Information__c
                                                      WHERE Case__c =: caseId];
        
        return claimantInfo;
    }
}