force-app/main/default/objects/Case/fields/Claimant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__c</field>
            <operation>equals</operation>
            <valueField>$Source.ClaimantFirm__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ClaimantFirm__c.field-meta.xml
<CustomField>
    <fullName>ClaimantFirm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Claimant Firm)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Defendant Firm</inlineHelpText>
    <label>Defendant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Defendant Firm)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Defendant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Defendant_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases (Defendant Firm Team)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facilitator_Contact__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Facilitator_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Facilitator Contact)</relationshipLabel>
    <relationshipName>Facilitator_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facilitator_Firm__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Facilitator Firm)</relationshipLabel>
    <relationshipName>Facilitator_Firm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defendant_Firm__c/Defendant_Firm__c.object-meta.xml
<CustomObject>
    <label>Defendant Firm</label>
    <nameField>
        <displayFormat>Defendant Firm - {00000}</displayFormat>
        <label>Defendant Firm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defendant Firms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/RemoveCaseTeams.cls
Public Class RemoveCaseTeams{


//CALLED FROM CASE TRIGGER ON CHANGE OF STATUS

Public Static void RemoveDefendantTeam(List<Case> Lst_OldCase,List<Case> Lst_NewCase){
     
     //Remove team tick box
     
     Map<String,String> Map_oldDefTeam = new Map<String,String>();
      
     for(Case oldc:Lst_OldCase){
         Map_oldDefTeam.put(oldc.id,oldc.Defendant_Firm_Team__c);
     }
     
     Set<String> Set_Case = new Set<String>();
     
     for(Case newc:Lst_NewCase){
     
         if(Map_oldDefTeam.get(newc.id) != newc.Defendant_Firm_Team__c){
             Set_Case.Add(newc.id);
         }
     }
     
     if(Set_Case.size()>0){
             Set<String> Set_Member = new Set<String>();
             Case[] Lst_Case = [Select id,Defendant_Firm__c From Case Where id in: Set_Case];
                
            CaseTeamMember[] CaseTeamMember = [Select MemberId,TeamRoleId,ParentId From CaseTeamMember where ParentId =:Set_Case AND TeamRole.Name =:'Defendant Handler'];       
           
            delete CaseTeamMember;
            
    }    
   /*
   for(CaseTeamMember mem:CaseTeamMember){
       Set_Member.add(mem.MemberId);   
   } 
   
    
    //CaseMemberHandler.RemoveTeam(Lst_Case[0].Defendant_Firm__c,CaseId,Set_Member);    
   */
    
}


Public Static void RemoveClaimantTeam(List<Case> Lst_OldCase,List<Case> Lst_NewCase){
    
      //Remove team tick box
     
     Map<String,String> Map_oldDefTeam = new Map<String,String>();
      
     for(Case oldc:Lst_OldCase){
         Map_oldDefTeam.put(oldc.id,oldc.Claimant_Firm_Team__c);
     }
     
     Set<String> Set_Case = new Set<String>();
     
     for(Case newc:Lst_NewCase){
     
         if(Map_oldDefTeam.get(newc.id) != newc.Claimant_Firm_Team__c){
             Set_Case.Add(newc.id);
         }
     }
     
     if(Set_Case.size()>0){
             Set<String> Set_Member = new Set<String>();
             Case[] Lst_Case = [Select id,Defendant_Firm__c From Case Where id in: Set_Case];
                
            CaseTeamMember[] CaseTeamMember = [Select MemberId,TeamRoleId,ParentId From CaseTeamMember where ParentId =:Set_Case AND TeamRole.Name =:'Claimant Handler'];       
           
            delete CaseTeamMember;
            
    }    
   /*
   for(CaseTeamMember mem:CaseTeamMember){
       Set_Member.add(mem.MemberId);   
   } 
   
    
    //CaseMemberHandler.RemoveTeam(Lst_Case[0].Defendant_Firm__c,CaseId,Set_Member);    
   */
    
}


Public Static void RemoveClaimantSupervisor(List<Case> Lst_OldCase,List<Case> Lst_NewCase){
    
      //Remove team tick box
     
     Map<String,String> Map_oldDefTeam = new Map<String,String>();
      
     for(Case oldc:Lst_OldCase){
         Map_oldDefTeam.put(oldc.id,oldc.ClaimantFirm__c);
     }
     
     Set<String> Set_Case = new Set<String>();
     
     for(Case newc:Lst_NewCase){
     
         if(Map_oldDefTeam.get(newc.id) != newc.ClaimantFirm__c){
             Set_Case.Add(newc.id);
         }
     }
     
     if(Set_Case.size()>0){
             Set<String> Set_Member = new Set<String>();
             Case[] Lst_Case = [Select id,Defendant_Firm__c From Case Where id in: Set_Case];
                
            CaseTeamMember[] CaseTeamMember = [Select MemberId,TeamRoleId,ParentId From CaseTeamMember where ParentId =:Set_Case AND TeamRole.Name =:'Claimant Supervisor'];       
           
            delete CaseTeamMember;
            
    }    
}


Public Static void RemoveDefendantSupervisor(List<Case> Lst_OldCase,List<Case> Lst_NewCase){
     
     //Remove team tick box
     
     Map<String,String> Map_oldDefTeam = new Map<String,String>();
      
     for(Case oldc:Lst_OldCase){
         Map_oldDefTeam.put(oldc.id,oldc.Defendant_Firm__c);
     }
     
     Set<String> Set_Case = new Set<String>();
     
     for(Case newc:Lst_NewCase){
     
         if(Map_oldDefTeam.get(newc.id) != newc.Defendant_Firm__c){
             Set_Case.Add(newc.id);
         }
     }
     
     if(Set_Case.size()>0){
             Set<String> Set_Member = new Set<String>();
             Case[] Lst_Case = [Select id,Defendant_Firm__c From Case Where id in: Set_Case];
                
            CaseTeamMember[] CaseTeamMember = [Select MemberId,TeamRoleId,ParentId From CaseTeamMember where ParentId =:Set_Case AND TeamRole.Name =:'Defendant Supervisor'];       
           
            delete CaseTeamMember;
            
    }    
   /*
   for(CaseTeamMember mem:CaseTeamMember){
       Set_Member.add(mem.MemberId);   
   } 
   
    
    //CaseMemberHandler.RemoveTeam(Lst_Case[0].Defendant_Firm__c,CaseId,Set_Member);    
   */
    
}

Public Static void RemoveFacilitator(List<Case> Lst_OldCase,List<Case> Lst_NewCase){
     
     //Remove team tick box
     
     Map<String,String> Map_oldFac = new Map<String,String>();
     Map<String,String> Map_oldFacCon = new Map<String,String>();
      
     for(Case oldc:Lst_OldCase){
         Map_oldFac.put(oldc.id,oldc.Facilitator_Firm__c);
         Map_oldFacCon.put(oldc.id,oldc.Facilitator_Contact__c);
         
     }
     
     Set<String> Set_Case = new Set<String>();
     
     for(Case newc:Lst_NewCase){
     
         if(Map_oldFac.get(newc.id) != newc.Facilitator_Firm__c){
             Set_Case.Add(newc.id);
             newc.Facilitator_Contact__c=null;
         }
         else if(Map_oldFacCon.get(newc.id) != newc.Facilitator_Contact__c){
             Set_Case.Add(newc.id);
         }
         
     }
     
     if(Set_Case.size()>0){
             Set<String> Set_Member = new Set<String>();
             Case[] Lst_Case = [Select id,Facilitator_Firm__c From Case Where id in: Set_Case];
                
            CaseTeamMember[] CaseTeamMember = [Select MemberId,TeamRoleId,ParentId From CaseTeamMember where ParentId =:Set_Case AND TeamRole.Name =:'Facilitator'];       
           
            delete CaseTeamMember;
            
    } 
    
    
       
   /*
   for(CaseTeamMember mem:CaseTeamMember){
       Set_Member.add(mem.MemberId);   
   } 
   
    
    //CaseMemberHandler.RemoveTeam(Lst_Case[0].Defendant_Firm__c,CaseId,Set_Member);    
   */
    
}


    
}