force-app/main/default/objects/Case/fields/ClaimantFirm__c.field-meta.xml
<CustomField>
    <fullName>ClaimantFirm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Claimant Firm)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Handler</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Arbitrator</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddClaimantSupervisorTeam.cls
Public Class AddClaimantSupervisorTeam{


@InvocableMethod
Public Static void AddSupervisorTeam(List<Id>  SupervisorId){
      
    Case[] Lst_Case = [Select id,ClaimantFirm__c From Case Where id in: SupervisorId];
    
    Set<String> Set_ClFirm = new Set<string>();
    for(Case c:Lst_Case){
        Set_ClFirm.add(c.ClaimantFirm__c);  
    }
    Contact[] lstContact = [Select id,AccountId From Contact where Role__c=:'Supervisor' AND AccountId in:Set_ClFirm AND Status__c='Active']; 
    
    Map<String,String> Map_TeamIdCaseId = new Map<String,String>();
    
    system.Debug('**lstContact**'+lstContact);
    Set<String> Set_Con = new Set<String>();
    for(Case c:Lst_Case){
        for( Contact con:lstContact){
              if(con.AccountId == c.ClaimantFirm__c){ 
                  Set_Con.Add(con.id);     
                Map_TeamIdCaseId.put(con.id,c.id); 
              }   
        }
    }
    system.Debug('****'+Map_TeamIdCaseId);
   
    
    
    CaseMemberHandler.AddtoCaseTeamIndividual('Claimant Supervisor',Map_TeamIdCaseId);
    //FirmMemberTeamHandler.AddCountupdateIndividual(Set_Con);
}

    
}