force-app/main/default/objects/Case/fields/Defendant_Firm__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Defendant Firm</inlineHelpText>
    <label>Defendant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Defendant Firm)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Defendant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Defendant_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases (Defendant Firm Team)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Handler</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Arbitrator</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defendant_Firm__c/Defendant_Firm__c.object-meta.xml
<CustomObject>
    <label>Defendant Firm</label>
    <nameField>
        <displayFormat>Defendant Firm - {00000}</displayFormat>
        <label>Defendant Firm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defendant Firms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/AddDefSupervisorTeam.cls
Public Class AddDefSupervisorTeam{


@InvocableMethod
Public Static void AddSupervisorTeam(List<Id>  SupervisorId){
      
    Case[] Lst_Case = [Select id,Defendant_Firm_Team__c,Defendant_Firm__c From Case Where id in: SupervisorId];
    
    Set<String> Set_DefFirm = new Set<string>();
    for(Case c:Lst_Case){
        Set_DefFirm.add(c.Defendant_Firm__c);  
    }
    Contact[] lstContact = [Select id,AccountId From Contact where Role__c=:'Supervisor' AND AccountId in:Set_DefFirm AND Status__c ='Active']; 
    
    Map<String,String> Map_TeamIdCaseId = new Map<String,String>();
    
    system.Debug('**lstContact**'+lstContact);
    
    Set<String> Set_Con = new Set<String>();
    String CaseId;
    for(Case c:Lst_Case){
        for( Contact con:lstContact){
              if(con.AccountId == c.Defendant_Firm__c){      
                Map_TeamIdCaseId.put(con.id,c.id);
                Set_Con.Add(con.id);
                CaseId=c.id; 
              }   
        }
    }
    system.Debug('****'+Map_TeamIdCaseId);
     
    CaseMemberHandler.AddtoCaseTeamIndividual('Defendant Supervisor',Map_TeamIdCaseId);  
    CaseNotificationHandler.NotifySupervisorsRegistration(Set_Con,'Defendant',CaseId );
   // FirmMemberTeamHandler.AddCountupdateIndividual(Set_Con);
     
}
    
}