force-app/main/default/objects/Case/fields/Defendant_Information__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Defendant Information</label>
    <referenceTo>Defendant_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defendant_Information__c/Defendant_Information__c.object-meta.xml
<CustomObject>
    <label>Defendant Information</label>
    <nameField>
        <displayFormat>Defendant - {000000}</displayFormat>
        <label>Defendant Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defendant Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Defendant_Information__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Defendant Information</relationshipLabel>
    <relationshipName>Defendant_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Defendant_Information__c/fields/Company_Employer_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Employer_Name__c</fullName>
    <label>Company / Employer Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defendant_Information__c/fields/Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_First_Name__c</fullName>
    <label>Contact First Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defendant_Information__c/fields/Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Last_Name__c</fullName>
    <label>Contact Last Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Defendant_Information__c/fields/Defendant_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Defendant_First_Name__c</fullName>
    <label>Defendant First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DefendantRelatedList.cls
public class DefendantRelatedList {

    @AuraEnabled
    public static List<Defendant_Information__c> getDefendantInfo(String caseId) {
        
        List<Defendant_Information__c> defendantInfo = [SELECT Id, 
                                                        Name,
                                                        Case__c ,
                                                        Company_Employer_Name__c ,
                                                        Contact_First_Name__c,
                                                        Contact_Last_Name__c,
                                                        Defendant_Date_of_Birth__c,
                                                        Defendant_First_Name__c,
                                                        Defendant_Last_Name__c,
                                                        Editable__c,
                                                        Defendant_Vehicle_Registration_Number__c,
                                                        Case__r.Status
                                                        FROM Defendant_Information__c
                                                        WHERE Case__c =: caseId];
        
        return defendantInfo;
    }
    
}