force-app/main/default/objects/Schedule_of_Losses__c/Schedule_of_Losses__c.object-meta.xml
<CustomObject>
    <label>Schedule of Losses</label>
    <nameField>
        <displayFormat>Sched {00000}</displayFormat>
        <label>Schedule of Losses No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Arbitration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Start_Date__c</fullName>
    <label>Arbitration Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Arbitrators_Award_Finalised__c.field-meta.xml
<CustomField>
    <fullName>Arbitrators_Award_Finalised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Arbitrators Award Finalised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Bilateral_referral_date_passed__c.field-meta.xml
<CustomField>
    <fullName>Bilateral_referral_date_passed__c</fullName>
    <formula>If(
AND(Case__r.Protocol__r.Bilateral_referral_days__c=0,Bilateral_referral_date__c  &lt;= Today()),true,
If(
OR(Bilateral_referral_date__c  &gt;= Today(),ISNULL(Bilateral_referral_date__c ) ),
false,true))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bilateral referral date passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Schedule of Losses</relationshipLabel>
    <relationshipName>Schedule_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimaint_Arbitration_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Claimaint_Arbitration_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimaint Arbitration Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimant_Accept_Decline__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Accept_Decline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimant Accept/Decline</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimant_Confirm_Documents_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Confirm_Documents_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimant Confirm Documents Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimant_Final_Offer_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Final_Offer_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimant Final Offer Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Accept_Decline__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Accept_Decline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Accept/Decline</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Arbitration_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Arbitration_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Arbitration Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Confirm_Documents_uploaded__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Confirm_Documents_uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Confirm Documents uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Final_Offer_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Final_Offer_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Final Offer Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Doc_Prep_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Doc_Prep_Start_Date__c</fullName>
    <label>Doc Prep Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Final_Offers_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Offers_Start_Date__c</fullName>
    <label>Final Offers Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/No_referral_date_passed__c.field-meta.xml
<CustomField>
    <fullName>No_referral_date_passed__c</fullName>
    <formula>If(OR(No_referral_date__c &gt; Today(),ISNULL(No_referral_date__c) ),false,true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No referral (date) passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Unilateral_referral_date_passed__c.field-meta.xml
<CustomField>
    <fullName>Unilateral_referral_date_passed__c</fullName>
    <formula>If(
AND(
Case__r.Protocol__r.Unilateral_referral_days__c =0,Unilateral_referral_date__c  &lt;= Today()),true,
If(OR(Unilateral_referral_date__c  &gt;= Today(),ISNULL(Unilateral_referral_date__c) ),
false,true))</formula>
    <label>Unilateral referral date passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NotifyClaimantTeamSubmitDocuments_test.cls
@istest

Public class NotifyClaimantTeamSubmitDocuments_test{


Public static testmethod void NotifyClaimantTeamSubmitDocumentsSOL1(){

    test.starttest();
    
           
         //   Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
        //    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
        //    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
        
            Test_InsertFirm_Contact_Team_TeamRole_2.insertContactUser();  
            Test_SetUpCaseProtocol_3.testCreateProtocol();
            
            List<Schedule_of_Losses__c> ScheduleofLosses = new List<Schedule_of_Losses__c>([Select id, Bilateral_referral_date_passed__c,No_referral_date_passed__c,Unilateral_referral_date_passed__c,
            Claimant_Accept_Decline__c, Defendant_Accept_Decline__c,Arbitrators_Award_Finalised__c,  Claimant_Final_Offer_Confirmed__c,Defendant_Final_Offer_Confirmed__c,Claimant_Confirm_Documents_Uploaded__c, 
             Defendant_Confirm_Documents_uploaded__c,   Arbitration_Start_Date__c,Doc_Prep_Start_Date__c,Final_Offers_Start_Date__c,Name,Case__c,Defendant_Arbitration_Submitted__c,Claimaint_Arbitration_Submitted__c From Schedule_of_Losses__c]);
         
           ScheduleofLosses[0].Defendant_Confirm_Documents_uploaded__c=true;
           update ScheduleofLosses;
         //  ScheduleofLosses[0].Claimant_Confirm_Documents_Uploaded__c=true;
          // update ScheduleofLosses;
    test.stoptest();
    

}
Public static testmethod void NotifyClaimantTeamSubmitDocumentsSOL2(){

    test.starttest();
    
           
         //   Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
        //    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
        //    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
        
            Test_InsertFirm_Contact_Team_TeamRole_2.insertContactUser();  
            Test_SetUpCaseProtocol_3.testCreateProtocol();
            
            List<Schedule_of_Losses__c> ScheduleofLosses = new List<Schedule_of_Losses__c>([Select id, Bilateral_referral_date_passed__c,No_referral_date_passed__c,Unilateral_referral_date_passed__c,
            Claimant_Accept_Decline__c, Defendant_Accept_Decline__c,Arbitrators_Award_Finalised__c,  Claimant_Final_Offer_Confirmed__c,Defendant_Final_Offer_Confirmed__c,Claimant_Confirm_Documents_Uploaded__c, 
             Defendant_Confirm_Documents_uploaded__c,   Arbitration_Start_Date__c,Doc_Prep_Start_Date__c,Final_Offers_Start_Date__c,Name,Case__c,Defendant_Arbitration_Submitted__c,Claimaint_Arbitration_Submitted__c From Schedule_of_Losses__c]);
         
       //    ScheduleofLosses[0].Defendant_Confirm_Documents_uploaded__c=true;
        //   update ScheduleofLosses;
           ScheduleofLosses[0].Claimant_Confirm_Documents_Uploaded__c=true;
           update ScheduleofLosses;
    test.stoptest();
    

}


}