force-app/main/default/objects/Schedule_of_Losses__c/Schedule_of_Losses__c.object-meta.xml
<CustomObject>
    <label>Schedule of Losses</label>
    <nameField>
        <displayFormat>Sched {00000}</displayFormat>
        <label>Schedule of Losses No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Schedule of Losses</relationshipLabel>
    <relationshipName>Schedule_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Arbitration_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Arbitration_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Arbitration Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NotifyClaimantTeamAcceptDeclineSOL_test.cls
@istest

Public class NotifyClaimantTeamAcceptDeclineSOL_test{


Public static testmethod void NotifyClaimantTeamAcceptDeclineSOL1(){

    test.starttest();
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();            
                       
            Test_SetUpCaseProtocol_2.testCreateProtocol();
                       
            Schedule_of_Losses__c[] ScheduleLosses = [Select id,Defendant_Arbitration_Submitted__c,Case__c From Schedule_of_Losses__c];
            
            ScheduleLosses[0].Defendant_Arbitration_Submitted__c =  true;
            
            update ScheduleLosses;
            
    test.stoptest();
    

}



}