force-app/main/default/objects/Schedule_of_Losses__c/Schedule_of_Losses__c.object-meta.xml
<CustomObject>
    <label>Schedule of Losses</label>
    <nameField>
        <displayFormat>Sched {00000}</displayFormat>
        <label>Schedule of Losses No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Arbitrators_Award_Finalised__c.field-meta.xml
<CustomField>
    <fullName>Arbitrators_Award_Finalised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Arbitrators Award Finalised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Invite_Arbitrator__c.field-meta.xml
<CustomField>
    <fullName>Invite_Arbitrator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invite Arbitrator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NotifyArbitratorSubmitsSOL_test.cls
@istest

Public class NotifyArbitratorSubmitsSOL_test{


Public static testmethod void NotifyArbitratorSubmitsSOL1(){

    test.starttest();
           //  Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPARB2@noemail.com','ARB2');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
            Test_SetUpCaseProtocol_3.testCreateProtocol();
            
            List<Schedule_of_Losses__c> ScheduleofLosses = new List<Schedule_of_Losses__c>([Select id,Arbitrators_Award_Finalised__c, Invite_Arbitrator__c From Schedule_of_Losses__c]);
         
         
           ScheduleofLosses[0].Arbitrators_Award_Finalised__c = true;
           update ScheduleofLosses;
           
           ScheduleofLosses[0].Invite_Arbitrator__c=true;           
           update ScheduleofLosses;
    
    test.stoptest();
    

}



}