force-app/main/default/objects/Incident_Information__c/Incident_Information__c.object-meta.xml
<CustomObject>
    <label>Incident Information</label>
    <nameField>
        <displayFormat>Incident - {000000}</displayFormat>
        <label>Incident Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incident_Information__c/fields/City2__c.field-meta.xml
<CustomField>
    <fullName>City2__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incident_Information__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Incident_Information__c/fields/Incident_Date__c.field-meta.xml
<CustomField>
    <fullName>Incident_Date__c</fullName>
    <label>Incident Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Incident_Information__c/fields/Incident_Matching_Date__c.field-meta.xml
<CustomField>
    <fullName>Incident_Matching_Date__c</fullName>
    <formula>DATEVALUE(Incident_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incident Matching Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Incident_Information__c/fields/State_County__c.field-meta.xml
<CustomField>
    <fullName>State_County__c</fullName>
    <label>State / County</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IncidentMatchingController_test.cls
@istest

Public class IncidentMatchingController_test{


Public static testmethod void setupgrid(){

    test.starttest();
            
           Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
           Test_SetUpCaseProtocol_2.testCreateProtocol();
           
           List<Incident_Information__c> matchingIncidents = [SELECT Id, State_County__c, Postal_Code__c, Address_Line_1__c, City2__c, Country__c,  Incident_Matching_Date__c , Incident_Date__c, OwnerId, Description__c, Name from Incident_Information__c ];
        
          
           User[] user1 = [Select id From User where username='handler4@testINAP.com']; 
    
    
    
      matchingIncidents[0].OwnerId = user1[0].id;
      update matchingIncidents;                                  
   
    System.runAs(user1[0]) {
              IncidentMatchingController.getIncidents(matchingIncidents[0].Postal_Code__c, matchingIncidents[0].Incident_Matching_Date__c,''); 
          
    }
          
            
    test.stoptest();
    

}



}