force-app/main/default/objects/ContentVersion/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <label>Case Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Ghost_Draft_Doc__c.field-meta.xml
<CustomField>
    <fullName>Ghost_Draft_Doc__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ghost Draft Doc</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/INAP_Doc_Type__c.field-meta.xml
<CustomField>
    <fullName>INAP_Doc_Type__c</fullName>
    <label>INAP Doc Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>INAP_Document_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Sharing_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Permissions__c</fullName>
    <label>Sharing Permissions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Sharing_Permissions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Document_Sharing_Permissions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Private</fullName>
    </customValue>
    <customValue>
        <fullName>Shared</fullName>
        <default>true</default>
        <label>Shared - (Claimant, Defendant and Facilitator)</label>
    </customValue>
    <masterLabel>Document Sharing Permissions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/INAP_Document_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Written Argument</fullName>
    </customValue>
    <customValue>
        <fullName>Arbitration Requirements</fullName>
    </customValue>
    <customValue>
        <fullName>Earlier Award</fullName>
    </customValue>
    <customValue>
        <fullName>Case Law</fullName>
    </customValue>
    <customValue>
        <fullName>Argument Other</fullName>
    </customValue>
    <customValue>
        <fullName>GTA Payment Pack</fullName>
    </customValue>
    <customValue>
        <fullName>Hire Invoice</fullName>
    </customValue>
    <customValue>
        <fullName>Impecuniosity Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Hire Rate and Period Evidence</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Hire Other</fullName>
    </customValue>
    <customValue>
        <fullName>Wage Loss Statement</fullName>
    </customValue>
    <customValue>
        <fullName>Schedule of Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Invoice</fullName>
    </customValue>
    <customValue>
        <fullName>Estimate</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Loss Other</fullName>
    </customValue>
    <customValue>
        <fullName>GP Report</fullName>
    </customValue>
    <customValue>
        <fullName>Accident &amp; Emergency</fullName>
    </customValue>
    <customValue>
        <fullName>Orthopaedic</fullName>
    </customValue>
    <customValue>
        <fullName>Psychiatrist</fullName>
    </customValue>
    <customValue>
        <fullName>Psychologist</fullName>
    </customValue>
    <customValue>
        <fullName>Ear nose and throat</fullName>
    </customValue>
    <customValue>
        <fullName>Nuero surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Neurology</fullName>
    </customValue>
    <customValue>
        <fullName>Gastric</fullName>
    </customValue>
    <customValue>
        <fullName>Vascular</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology</fullName>
    </customValue>
    <customValue>
        <fullName>Plastic Surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Hand surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Genito- Urinary</fullName>
    </customValue>
    <customValue>
        <fullName>Opthalmic</fullName>
    </customValue>
    <customValue>
        <fullName>Commencement</fullName>
    </customValue>
    <masterLabel>INAP Document Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_ContentSetup.cls
Public Class Test_ContentSetup{


Public static void SetupContent(){
    
   Case[] CaseDoc = [Select CaseNumber from Case];
        
   String DocName = 'Commencement';
   Blob requestresponse = blob.valueof('testing');
   Network[] Nwork = [SELECT Id,Name FROM Network limit 1];
    
    ContentVersion contentVersion = new ContentVersion(
      Title = DocName,
      PathOnClient = DocName,
      Sharing_Permissions__c = 'Shared',
      Case_Id__c = CaseDoc[0].id,
      VersionData = requestresponse,
      INAP_Doc_Type__c = 'Commencement',
      Ghost_Draft_Doc__c =true,
      NetworkId = Nwork[0].id,
      IsMajorVersion = true
    );
    insert contentVersion;    
    
    system.debug('**CV**'+contentVersion);
    List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument where title=:DocName];

    system.debug('**documents**'+documents);
    //create ContentDocumentLink  record 
    
    ContentDocumentLink cdl = New ContentDocumentLink();
    cdl.LinkedEntityId = CaseDoc[0].id;
    cdl.ContentDocumentId = documents[0].Id;
    cdl.shareType = 'V';
    insert cdl;


}




}