force-app/main/default/objects/ContentVersion/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Content Versions</relationshipLabel>
    <relationshipName>Content_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <label>Case Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/INAP_Doc_Type__c.field-meta.xml
<CustomField>
    <fullName>INAP_Doc_Type__c</fullName>
    <label>INAP Doc Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>INAP_Document_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Sharing_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Permissions__c</fullName>
    <label>Sharing Permissions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Sharing_Permissions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Uploaded_By__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_By__c</fullName>
    <label>Uploaded By:</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Case_Team_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Case_Team_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Claimant Handler</fullName>
    </customValue>
    <customValue>
        <fullName>Defendant Handler</fullName>
    </customValue>
    <masterLabel>Case Team Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Document_Sharing_Permissions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Private</fullName>
    </customValue>
    <customValue>
        <fullName>Shared</fullName>
        <default>true</default>
        <label>Shared - (Claimant, Defendant and Facilitator)</label>
    </customValue>
    <masterLabel>Document Sharing Permissions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/INAP_Document_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Written Argument</fullName>
    </customValue>
    <customValue>
        <fullName>Arbitration Requirements</fullName>
    </customValue>
    <customValue>
        <fullName>Earlier Award</fullName>
    </customValue>
    <customValue>
        <fullName>Case Law</fullName>
    </customValue>
    <customValue>
        <fullName>Argument Other</fullName>
    </customValue>
    <customValue>
        <fullName>GTA Payment Pack</fullName>
    </customValue>
    <customValue>
        <fullName>Hire Invoice</fullName>
    </customValue>
    <customValue>
        <fullName>Impecuniosity Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Hire Rate and Period Evidence</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Hire Other</fullName>
    </customValue>
    <customValue>
        <fullName>Wage Loss Statement</fullName>
    </customValue>
    <customValue>
        <fullName>Schedule of Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Invoice</fullName>
    </customValue>
    <customValue>
        <fullName>Estimate</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Loss Other</fullName>
    </customValue>
    <customValue>
        <fullName>GP Report</fullName>
    </customValue>
    <customValue>
        <fullName>Accident &amp; Emergency</fullName>
    </customValue>
    <customValue>
        <fullName>Orthopaedic</fullName>
    </customValue>
    <customValue>
        <fullName>Psychiatrist</fullName>
    </customValue>
    <customValue>
        <fullName>Psychologist</fullName>
    </customValue>
    <customValue>
        <fullName>Ear nose and throat</fullName>
    </customValue>
    <customValue>
        <fullName>Nuero surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Neurology</fullName>
    </customValue>
    <customValue>
        <fullName>Gastric</fullName>
    </customValue>
    <customValue>
        <fullName>Vascular</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology</fullName>
    </customValue>
    <customValue>
        <fullName>Plastic Surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Hand surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Genito- Urinary</fullName>
    </customValue>
    <customValue>
        <fullName>Opthalmic</fullName>
    </customValue>
    <masterLabel>INAP Document Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DocumentGridController2.cls
public class DocumentGridController2 {

    @AuraEnabled
    public static List<ContentVersion> getFiles(String caseID) {
        
        
        String LOGGEDINUSER = UserAccessRights.ProfileName(caseID);
        
        ContentDocumentLink[] DocumentLink = [SELECT LinkedEntityId,ContentDocumentId FROM ContentDocumentLink where LinkedEntityId =:caseID  ];      

        Set<String> set_docId = new Set<String>();
         for(ContentDocumentLink doc:DocumentLink){
             set_docId.add(doc.ContentDocumentId);    
         }
        
        
        
        List<ContentVersion> files = [SELECT Id,
                                      Case_Id__c,
                                      Case__r.Status,
                                      ContentDocumentId,
                                      Sharing_Permissions__c,
                                      INAP_Doc_Type__c,
                                      CreatedbyId,
                                      Title,
                                      ContentModifiedDate,
                                      Uploaded_By__c
                                      FROM ContentVersion
                                      WHERE ContentDocumentId in:set_docId];
        
        system.debug('******'+ files);
        
        List<ContentVersion> FilteredFiles = new List<ContentVersion>();
        
        for (ContentVersion fFiles: files) {
             if (fFiles.Sharing_Permissions__c == 'Private' && fFiles.Uploaded_By__c == LOGGEDINUSER && fFiles.Uploaded_By__c == 'Claimant Handler' ){
                FilteredFiles.add(fFiles);
            }
            else if (fFiles.Sharing_Permissions__c == 'Private' && fFiles.Uploaded_By__c == LOGGEDINUSER && fFiles.Uploaded_By__c == 'Defendant Handler') {
                FilteredFiles.add(fFiles);
            }
            else if (fFiles.Sharing_Permissions__c == 'Shared' && LOGGEDINUSER != 'Arbitrator') {
               FilteredFiles.add(fFiles);
            }
            else if (fFiles.CreatedbyId == userInfo.getUserId() && LOGGEDINUSER == 'Arbitrator') {
               FilteredFiles.add(fFiles);
            }
        }
        
        
        return FilteredFiles;
    }
    
    // method for update records after inline editing  
    @AuraEnabled
    public static List < ContentVersion > saveContentVersion(List<ContentVersion> lstContentVersion) {
        update lstContentVersion;
        return lstContentVersion;
    }
    
  // method for fetch picklist values dynamic  
    @AuraEnabled
    public static List < String > getselectOptions(sObject objObject, string fld) {
        system.debug('objObject --->' + objObject);
        system.debug('fld --->' + fld);
        List < String > allOpts = new list < String > ();
        // Get the object type of the SObject.
        Schema.sObjectType objType = objObject.getSObjectType();
        
        // Describe the SObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        // Get a map of fields for the SObject
        map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
        
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            fieldMap.get(fld).getDescribe().getPickListValues();
        
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }
        system.debug('allOpts ---->' + allOpts);
        allOpts.sort();
        return allOpts;
    }
    
}