force-app/main/default/objects/ContentVersion/fields/INAP_Doc_Type__c.field-meta.xml
<CustomField>
    <fullName>INAP_Doc_Type__c</fullName>
    <label>INAP Doc Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>INAP_Document_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Sharing_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Sharing_Permissions__c</fullName>
    <label>Sharing Permissions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Sharing_Permissions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Document_Sharing_Permissions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Private</fullName>
    </customValue>
    <customValue>
        <fullName>Shared</fullName>
        <default>true</default>
        <label>Shared - (Claimant, Defendant and Facilitator)</label>
    </customValue>
    <masterLabel>Document Sharing Permissions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/INAP_Document_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Written Argument</fullName>
    </customValue>
    <customValue>
        <fullName>Arbitration Requirements</fullName>
    </customValue>
    <customValue>
        <fullName>Earlier Award</fullName>
    </customValue>
    <customValue>
        <fullName>Case Law</fullName>
    </customValue>
    <customValue>
        <fullName>Argument Other</fullName>
    </customValue>
    <customValue>
        <fullName>GTA Payment Pack</fullName>
    </customValue>
    <customValue>
        <fullName>Hire Invoice</fullName>
    </customValue>
    <customValue>
        <fullName>Impecuniosity Documents</fullName>
    </customValue>
    <customValue>
        <fullName>Hire Rate and Period Evidence</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Hire Other</fullName>
    </customValue>
    <customValue>
        <fullName>Wage Loss Statement</fullName>
    </customValue>
    <customValue>
        <fullName>Schedule of Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Invoice</fullName>
    </customValue>
    <customValue>
        <fullName>Estimate</fullName>
    </customValue>
    <customValue>
        <fullName>Financial Loss Other</fullName>
    </customValue>
    <customValue>
        <fullName>GP Report</fullName>
    </customValue>
    <customValue>
        <fullName>Accident &amp; Emergency</fullName>
    </customValue>
    <customValue>
        <fullName>Orthopaedic</fullName>
    </customValue>
    <customValue>
        <fullName>Psychiatrist</fullName>
    </customValue>
    <customValue>
        <fullName>Psychologist</fullName>
    </customValue>
    <customValue>
        <fullName>Ear nose and throat</fullName>
    </customValue>
    <customValue>
        <fullName>Nuero surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Neurology</fullName>
    </customValue>
    <customValue>
        <fullName>Gastric</fullName>
    </customValue>
    <customValue>
        <fullName>Vascular</fullName>
    </customValue>
    <customValue>
        <fullName>Oncology</fullName>
    </customValue>
    <customValue>
        <fullName>Plastic Surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Hand surgeon</fullName>
    </customValue>
    <customValue>
        <fullName>Genito- Urinary</fullName>
    </customValue>
    <customValue>
        <fullName>Opthalmic</fullName>
    </customValue>
    <masterLabel>INAP Document Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DocumentGridController2_test.cls
@istest

Public class DocumentGridController2_test{


Public static testmethod void setupgrid(){

    test.starttest();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            
            Test_SetUpCaseProtocol_2.testCreateProtocol();
            
            Test_ContentSetup.SetupContent();
            
            Case[] CaseDoc = [Select CaseNumber from Case];
            DocumentGridController2.getFiles(CaseDoc[0].id);
            
            ContentVersion[] files = [SELECT Id,INAP_Doc_Type__c,Sharing_Permissions__c FROM ContentVersion];
            
            DocumentGridController2.saveContentVersion(files);
            
            sObject s = new ContentVersion();
            s= files[0];
            
            DocumentGridController2.getselectOptions(s,'Sharing_Permissions__c');
            
            
    test.stoptest();
    

}



}