force-app/main/default/objects/Case_Staging_Table__c/Case_Staging_Table__c.object-meta.xml
<CustomObject>
    <label>Case Staging Table</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Case Staging id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Staging Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Staging_Table__c/fields/Mapped_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mapped Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Case Staging Table</relationshipLabel>
    <relationshipName>Case_Staging_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseMatchingUtility_test.cls
@istest

Public class CaseMatchingUtility_test{


Public static testmethod void CaseMatchingUtility1(){

    test.starttest();
        Test_InsertProtocolOptions.InsertProtocolOptions();
        Test_Staging_Matching.testCreateProtocol ();
        
        
        Test_Staging_Matching.SetUpAdminUser();
        
        Test_Staging_Matching.SetupMatching();
        
        Protocol__c[] testProtocol = [Select id from Protocol__c ]; 
        
        Case_Staging_Table__c[] CaseStagingTable = [Select id,Mapped_Protocol__c FROM Case_Staging_Table__c];
        
        CaseStagingTable[0].Mapped_Protocol__c = testProtocol[0].id;
        update CaseStagingTable;
        
        List<Id> ids = new List<Id>();
        
        for(Case_Staging_Table__c t:CaseStagingTable){
            ids.add(t.id);
        }
        
        
        CaseMatchingUtility.ProcessImportedData (ids);
        
    test.stoptest();
    

}



}