force-app/main/default/objects/Account/recordTypes/Facilitator.recordType-meta.xml
<RecordType>
    <fullName>Facilitator</fullName>
    <active>false</active>
    <description>Facilitator</description>
    <label>Facilitator</label>
</RecordType>

force-app/main/default/objects/Case/fields/Arbitration_Firm__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arbitration Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Arbitration Firm)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitrator_Accept_Decline__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Accept_Decline__c</fullName>
    <inlineHelpText>Arbitrator responds to invitation to arbitrate case</inlineHelpText>
    <label>Arbitrator Response</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Arbitrator_Contact__c.field-meta.xml
<CustomField>
    <fullName>Arbitrator_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arbitrator Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Arbitration_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Arbitrator Contact)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Claimant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__c</field>
            <operation>equals</operation>
            <valueField>$Source.ClaimantFirm__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ClaimantFirm__c.field-meta.xml
<CustomField>
    <fullName>ClaimantFirm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Claimant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Claimant Firm)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Accept_Decline_Date__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Accept_Decline_Date__c</fullName>
    <label>Defendant Accept/Decline Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Accept_Reject__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Accept_Reject__c</fullName>
    <label>Defendant Accept/Reject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Agree_to_Arbitration_Process__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Agree_to_Arbitration_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant - Agree to Arbitration Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Defendant Firm</inlineHelpText>
    <label>Defendant Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Defendant Firm)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendant_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Defendant Firm Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Firm_Team__c.Firm__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Defendant_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Cases (Defendant Firm Team)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Defendent_rejection_reason__c.field-meta.xml
<CustomField>
    <fullName>Defendent_rejection_reason__c</fullName>
    <label>Defendent rejection reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facilitator_Contact__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Facilitator_Firm__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Facilitator Contact)</relationshipLabel>
    <relationshipName>Facilitator_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Facilitator_Firm__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator Firm</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Service Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Facilitator Firm)</relationshipLabel>
    <relationshipName>Facilitator_Firm</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Handler</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Arbitrator</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Defendant_Firm__c/Defendant_Firm__c.object-meta.xml
<CustomObject>
    <label>Defendant Firm</label>
    <nameField>
        <displayFormat>Defendant Firm - {00000}</displayFormat>
        <label>Defendant Firm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defendant Firms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Defendant_Firm__c/fields/Firm__c.field-meta.xml
<CustomField>
    <fullName>Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Defendant Firms</relationshipLabel>
    <relationshipName>Defendant_Firms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Defendant_Firm__c/fields/Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Firm Team</label>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Defendant Firms</relationshipLabel>
    <relationshipName>Defendant_Firms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Firm_Team__c/Firm_Team__c.object-meta.xml
<CustomObject>
    <label>Firm Team</label>
    <nameField>
        <label>Firm Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firm Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Firm_Team__c/fields/Firm__c.field-meta.xml
<CustomField>
    <fullName>Firm__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Firm Teams</relationshipLabel>
    <relationshipName>Firm_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CaseQuickActions_test.cls
@istest

Public class CaseQuickActions_test{

Public static testmethod void CaseQuickActions0(){
        test.starttest();
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPQUICK1@noemail.com','quik1');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            User[] user1 = [Select id From User where username='handler1@testINAP.com']; 
   
            System.runAs(user1[0]) {
                  Test_SetUpCaseProtocol_1.testCreateProtocol();
            }
            
     test.stoptest();       
}

Public static testmethod void CaseQuickActions1(){

    test.starttest();
            
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPQUICK1@noemail.com','quik1');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_SetUpCaseProtocol_1.testCreateProtocol();
           
           
            Case cs = [Select id from Case limit 1];
            PageReference QuickActions = Page.QuickActionsCase;  
            QuickActions .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(QuickActions);
            
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            CaseQuickActions Quick  = new CaseQuickActions(sc);
            
            
            Account[] FirmCl = [Select id from Account where Name = 'Legalsmiths'];
            Quick.CaseQuick.ClaimantFirm__c = FirmCl[0].id;
            Update Quick.CaseQuick;
            
             
             Account[] FirmDef = [Select id from Account where Name = 'Insuresmiths'];
             Quick.CaseQuick.Defendant_Firm__c = FirmDef[0].id; 
             Quick.CaseQuick.Subject = 'Test';
                                   
             Quick.addDefendentFirm();
            
         
            Quick.ShowFirmTeamsClaimant();
            Firm_Team__c[] testCl = [Select Firm__c From Firm_Team__c where Firm__c=:FirmCl[0].id];
            Quick.ClaimFirm = testCl[0].id;
            Quick.updateClaimTeam();
            
            
            Quick.ShowFirmTeamsDefendant();
            Firm_Team__c[] testDef = [Select Firm__c From Firm_Team__c where Firm__c=:FirmDef[0].id];
            Quick.DefFirm = testDef[0].id;
            
            Quick.updateDefTeam();
            
           /* 
            Quick.updaterefer();
            system.debug('**CASEREFER**'+Quick.CaseQuick.Status);
            
            Quick.CaseQuick.Defendant_Accept_Reject__c='Accept';
            Quick.CaseQuick.Defendant_Agree_to_Arbitration_Process__c=true;
            Quick.AcceptReject();
           */ 
           
            
            
            
    test.stoptest();
    

}

Public static testmethod void CaseQuickActions1a(){

    test.starttest();
            
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPQUICK1@noemail.com','quik1');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_SetUpCaseProtocol_1.testCreateProtocol();
           
              TestDateghostDraft.Setup();   
              
            Case cs = [Select id from Case limit 1];
            PageReference QuickActions = Page.QuickActionsCase;  
            QuickActions .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(QuickActions);
            
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            CaseQuickActions Quick  = new CaseQuickActions(sc);
            
            
            Account[] FirmCl = [Select id from Account where Name = 'Legalsmiths'];
            Quick.CaseQuick.ClaimantFirm__c = FirmCl[0].id;
         
        
             Account[] FirmDef = [Select id from Account where Name = 'Insuresmiths'];
             Quick.CaseQuick.Defendant_Firm__c = FirmDef[0].id; 
             Quick.CaseQuick.Subject = 'Test';
                                   
          
            Firm_Team__c[] testCl = [Select Firm__c From Firm_Team__c where Firm__c=:FirmCl[0].id];
            Quick.CaseQuick.Claimant_Firm_Team__c = testCl[0].id;
         
         
            Firm_Team__c[] testDef = [Select Firm__c From Firm_Team__c where Firm__c=:FirmDef[0].id];
            Quick.CaseQuick.Defendant_Firm_Team__c = testDef[0].id;
            Quick.CaseQuick.Defendant_Accept_Reject__c='Accept';
            Quick.CaseQuick.Defendant_Agree_to_Arbitration_Process__c=true;
            
            Update Quick.CaseQuick;
            
          
            Quick.updaterefer();
            system.debug('**CASEREFER**'+Quick.CaseQuick.Status);
            
            
           
            
            
            
    test.stoptest();
    

}

Public static testmethod void CaseQuickActions2(){

    test.starttest();
            //Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPQUICK2@noemail.com','quik2');
            
            //Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            //Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
            //Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
            Test_InsertFirm_Contact_Team_TeamRole_2.insertContactUser();
            Test_SetUpCaseProtocol_2a.testCreateProtocol();
            
            Case cs = [Select id from Case limit 1];
            PageReference QuickActions = Page.QuickActionsCase;  
            QuickActions .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(QuickActions);
            
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            
            CaseQuickActions Quick  = new CaseQuickActions(sc);
            
            
            
            
            Account[] FirmFac = [Select id from Account where Name = 'Facilitate'];
            
            Quick.CaseQuick.Facilitator_Firm__c=FirmFac[0].id; 
            Quick.Facilitator();
            
            Contact[] Facilitator = [Select id from Contact where Role__c = 'Facilitator'];            
            Quick.FacCon = Facilitator[0].id;            
            Quick.CaseQuick.Facilitator_Contact__c = Quick.FacCon;            
            
            Quick.updateFacCon();
            
           
            
            
            Quick.ShowActions();
            Quick.HideActions();
            
            Quick.AgreeArbitration();
            Quick.ClaimantSubmitSOL();
             
            Quick.ClaimantFinalise();
           
            
            
            
            
            
    test.stoptest();
    

}
Public static testmethod void CaseQuickActions2aa(){

    test.starttest();
            //Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPQUICK2@noemail.com','quik2');
            
            //Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            //Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
            //Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
            
            Test_InsertFirm_Contact_Team_TeamRole_2.insertContactUser();
            Test_SetUpCaseProtocol_2a.testCreateProtocol();
            
            
            TestDateghostDraft.Setup();
            
            Case cs = [Select id from Case limit 1];
            PageReference QuickActions = Page.QuickActionsCase;  
            QuickActions .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(QuickActions);
            
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            
            CaseQuickActions Quick  = new CaseQuickActions(sc);
         
            
            Account[] FirmArb = [Select id from Account where Name = 'Arbitrator'];
            Quick.CaseQuick.Arbitration_Firm__c = FirmArb[0].id;
            Quick.Arbitrator();
            
            Contact[] Arbitrator = [Select id from Contact where Role__c = 'Arbitrator'];            
            Quick.ArbCon = Arbitrator[0].id;            
            Quick.CaseQuick.Arbitrator_Contact__c = Quick.ArbCon;
            Quick.updateArbCon(); 
            
       
            Quick.CaseQuick.Arbitrator_Accept_Decline__c='Accept';
            Update Quick.CaseQuick;
            Quick.AcceptReject();
            
            
            
            
    test.stoptest();
    

}

Public static testmethod void CaseQuickActions2a(){

    test.starttest();
            
            
           // Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPQUICK1@noemail.com','quik1');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_SetUpCaseProtocol_1.testCreateProtocol();
           
              TestDateghostDraft.Setup();   
              
            Case cs = [Select id from Case limit 1];
            PageReference QuickActions = Page.QuickActionsCase;  
            QuickActions .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(QuickActions);
            
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            CaseQuickActions Quick  = new CaseQuickActions(sc);
            
            
            Account[] FirmCl = [Select id from Account where Name = 'Legalsmiths'];
            Quick.CaseQuick.ClaimantFirm__c = FirmCl[0].id;
         
        
             Account[] FirmDef = [Select id from Account where Name = 'Insuresmiths'];
             Quick.CaseQuick.Defendant_Firm__c = FirmDef[0].id; 
             Quick.CaseQuick.Subject = 'Test';
                                   
          
            Firm_Team__c[] testCl = [Select Firm__c From Firm_Team__c where Firm__c=:FirmCl[0].id];
            Quick.CaseQuick.Claimant_Firm_Team__c = testCl[0].id;
         
         
            Firm_Team__c[] testDef = [Select Firm__c From Firm_Team__c where Firm__c=:FirmDef[0].id];
            Quick.CaseQuick.Defendant_Firm_Team__c = testDef[0].id;
            
            Update Quick.CaseQuick;
            
            Quick.loadClaimant();
            Quick.UpdateClaimant();
       
            Quick.loadDefedant();
            Quick.UpdateDefendant();
            Quick.ChangeDefendentFirm();
            Quick.ChangeDefendentFirmTeam();
            Quick.updateClaim();

            Quick.ShowArbitrator();
            Quick.ShowFacilitator();
            Quick.ShowDefendant();
            Quick.ShowClaimant();

            Quick.ArbitratorReset();
            Quick.checkMinRequirements();
                     
            
            test.stoptest();
    

}

Public static testmethod void CaseQuickActions2b(){

    test.starttest();
            
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPQUICK1@noemail.com','quik1');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_SetUpCaseProtocol_1.testCreateProtocol();
           
              TestDateghostDraft.Setup();   
              
            Case cs = [Select id from Case limit 1];
            PageReference QuickActions = Page.QuickActionsCase;  
            QuickActions .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(QuickActions);
            
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            CaseQuickActions Quick  = new CaseQuickActions(sc);
            
            
            Account[] FirmCl = [Select id from Account where Name = 'Legalsmiths'];
            Quick.CaseQuick.ClaimantFirm__c = FirmCl[0].id;
         
        
             Account[] FirmDef = [Select id from Account where Name = 'Insuresmiths'];
             Quick.CaseQuick.Defendant_Firm__c = FirmDef[0].id; 
             Quick.CaseQuick.Subject = 'Test';
                                   
          
            Firm_Team__c[] testCl = [Select Firm__c From Firm_Team__c where Firm__c=:FirmCl[0].id];
            Quick.CaseQuick.Claimant_Firm_Team__c = testCl[0].id;
         
         
            Firm_Team__c[] testDef = [Select Firm__c From Firm_Team__c where Firm__c=:FirmDef[0].id];
            Quick.CaseQuick.Defendant_Firm_Team__c = testDef[0].id;
            Quick.CaseQuick.Defendant_Accept_Reject__c='Accept';
            Quick.CaseQuick.Defendant_Agree_to_Arbitration_Process__c=true;
            
            Update Quick.CaseQuick;
            
          
             Quick.CancelCase(); 
            system.debug('**CASEREFER**'+Quick.CaseQuick.Status);
            
            
           
            
            
            
    test.stoptest();
    

}

Public static testmethod void CaseQuickActions2c(){

    test.starttest();
            
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPQUICK1@noemail.com','quik1');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_SetUpCaseProtocol_1.testCreateProtocol();
           
              TestDateghostDraft.Setup();   
              
            Case cs = [Select id from Case limit 1];
            PageReference QuickActions = Page.QuickActionsCase;  
            QuickActions .getParameters().put('id',cs.id);     
            
            Test.setCurrentPageReference(QuickActions);
            
            ApexPages.StandardController sc = new ApexPages.StandardController(cs);
            CaseQuickActions Quick  = new CaseQuickActions(sc);
            
            
            Account[] FirmCl = [Select id from Account where Name = 'Legalsmiths'];
            Quick.CaseQuick.ClaimantFirm__c = FirmCl[0].id;
         
        
             Account[] FirmDef = [Select id from Account where Name = 'Insuresmiths'];
             Quick.CaseQuick.Defendant_Firm__c = FirmDef[0].id; 
             Quick.CaseQuick.Subject = 'Test';
                                   
          
            Firm_Team__c[] testCl = [Select Firm__c From Firm_Team__c where Firm__c=:FirmCl[0].id];
            Quick.CaseQuick.Claimant_Firm_Team__c = testCl[0].id;
         
         
            Firm_Team__c[] testDef = [Select Firm__c From Firm_Team__c where Firm__c=:FirmDef[0].id];
            Quick.CaseQuick.Defendant_Firm_Team__c = testDef[0].id;
            Quick.CaseQuick.Defendant_Accept_Reject__c='Reject';
            Quick.CaseQuick.Defendant_Accept_Decline_Date__c = system.today();            
            Quick.CaseQuick.Defendent_rejection_reason__c = 'n/a';
            Quick.AcceptReject();
            
            
          
              
            system.debug('**CASEREFER**'+Quick.CaseQuick.Status);
            
            
           
            
            
            
    test.stoptest();
    

}



}