force-app/main/default/objects/Loss_Category__c/Loss_Category__c.object-meta.xml
<CustomObject>
    <label>Head of Loss</label>
    <nameField>
        <displayFormat>HL {00000}</displayFormat>
        <label>Head of Loss No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Head of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loss_Category__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Head_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loss_Category__c/fields/Loss_Category_Types__c.field-meta.xml
<CustomField>
    <fullName>Loss_Category_Types__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loss Category Types</label>
    <referenceTo>Loss_Category_Types__c</referenceTo>
    <relationshipName>Loss_Categoryies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loss_Category__c/fields/Schedule_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Schedule_of_Losses__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule of Losses</label>
    <referenceTo>Schedule_of_Losses__c</referenceTo>
    <relationshipName>Loss_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/Loss_Sub_Categories__c.object-meta.xml
<CustomObject>
    <label>Loss Item</label>
    <nameField>
        <displayFormat>Loss Item {0000000}</displayFormat>
        <label>Loss Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loss Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Arbitration_Accepted_Status__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Accepted_Status__c</fullName>
    <label>Arbitration Accepted Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Arbitration_Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Referred_By__c</fullName>
    <label>Arbitration Referred By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Claimant Handler</fullName>
            </value>
            <value>
                <fullName>Defendant Handler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Loss_Sub_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Defendant_Position__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Position__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Defendant Position</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Loss_Category__c.field-meta.xml
<CustomField>
    <fullName>Loss_Category__c</fullName>
    <label>Head of Loss</label>
    <referenceTo>Loss_Category__c</referenceTo>
    <relationshipLabel>Loss Items</relationshipLabel>
    <relationshipName>Loss_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Past_Future_Financial_Item__c.field-meta.xml
<CustomField>
    <fullName>Past_Future_Financial_Item__c</fullName>
    <formula>Past_Future_Financial_Losses__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Past/Future Financial Item</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Referred to Arbitration</fullName>
            </value>
            <value>
                <fullName>Arbitration Doc Prep</fullName>
            </value>
            <value>
                <fullName>Arbitration Final Offers</fullName>
            </value>
            <value>
                <fullName>Arbitrating</fullName>
            </value>
            <value>
                <fullName>Arbitrated</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <formula>Past_Future_Financial_Losses__r.Sub_Category__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loss_Sub_Categories__c/fields/Sum_Defendent_Position__c.field-meta.xml
<CustomField>
    <fullName>Sum_Defendent_Position__c</fullName>
    <label>Sum Defendent Position</label>
    <summarizedField>Defendant_Firm_Loss_Item_Position__c.Defendant_Position__c</summarizedField>
    <summaryForeignKey>Defendant_Firm_Loss_Item_Position__c.Loss_Sub_Category__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Merit__c/Merit__c.object-meta.xml
<CustomObject>
    <label>Merit</label>
    <nameField>
        <label>Merit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Merit__c/fields/Arbitration_Accepted_Status__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Accepted_Status__c</fullName>
    <label>Arbitration Accepted Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Arbitration_Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Arbitration_Referred_By__c</fullName>
    <label>Arbitration Referred By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Claimant Handler</fullName>
            </value>
            <value>
                <fullName>Defendant Handler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Defendant_Position__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Position__c</fullName>
    <label>Defendant Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Schedule_of_Losses__c.field-meta.xml
<CustomField>
    <fullName>Schedule_of_Losses__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule of Losses</label>
    <referenceTo>Schedule_of_Losses__c</referenceTo>
    <relationshipLabel>Merits</relationshipLabel>
    <relationshipName>Merits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Merit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negotiating</fullName>
                <default>true</default>
                <label>Negotiating</label>
            </value>
            <value>
                <fullName>Referred to Arbitration</fullName>
            </value>
            <value>
                <fullName>Arbitration Doc Prep</fullName>
            </value>
            <value>
                <fullName>Arbitrating</fullName>
            </value>
            <value>
                <fullName>Arbitration Final Offers</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Arbitrated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Past_Future_Financial_Losses__c/Past_Future_Financial_Losses__c.object-meta.xml
<CustomObject>
    <label>Past/Future Financial Losses</label>
    <nameField>
        <label>Past Financial Losses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Past/Future Financial Losses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Past_Future_Financial_Losses__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub Category</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/Schedule_of_Losses__c.object-meta.xml
<CustomObject>
    <label>Schedule of Losses</label>
    <nameField>
        <displayFormat>Sched {00000}</displayFormat>
        <label>Schedule of Losses No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule of Losses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Bilateral_referral_date_passed__c.field-meta.xml
<CustomField>
    <fullName>Bilateral_referral_date_passed__c</fullName>
    <formula>If(
AND(Case__r.Protocol__r.Bilateral_referral_days__c=0,Bilateral_referral_date__c  &lt;= Today()),true,
If(
OR(Bilateral_referral_date__c  &gt;= Today(),ISNULL(Bilateral_referral_date__c ) ),
false,true))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bilateral referral date passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Schedule of Losses</relationshipLabel>
    <relationshipName>Schedule_of_Losses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimaint_Arbitration_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Claimaint_Arbitration_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimaint Arbitration Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Claimant_Accept_Decline__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Accept_Decline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Claimant Accept/Decline</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Accept_Decline__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Accept_Decline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Accept/Decline</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Defendant_Arbitration_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Arbitration_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defendant Arbitration Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Doc_Prep_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Doc_Prep_Start_Date__c</fullName>
    <label>Doc Prep Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/No_referral_date_passed__c.field-meta.xml
<CustomField>
    <fullName>No_referral_date_passed__c</fullName>
    <formula>If(OR(No_referral_date__c &gt; Today(),ISNULL(No_referral_date__c) ),false,true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No referral (date) passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Unilateral_Arbitration_Overlap__c.field-meta.xml
<CustomField>
    <fullName>Unilateral_Arbitration_Overlap__c</fullName>
    <formula>If(AND(Unilateral_referral_date_passed__c=True,Unilateral_referral_date__c&gt;= Doc_Prep_Start_Date__c),True,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unilateral Arbitration Overlap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Unilateral_referral_date__c.field-meta.xml
<CustomField>
    <fullName>Unilateral_referral_date__c</fullName>
    <formula>if(Case__r.Protocol__r.Unilateral_referral_days__c=0,
Unilateral_Start_Date__c ,
Unilateral_Start_Date__c    +  Case__r.Protocol__r.Unilateral_referral_days__c-1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unilateral referral (End date)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Schedule_of_Losses__c/fields/Unilateral_referral_date_passed__c.field-meta.xml
<CustomField>
    <fullName>Unilateral_referral_date_passed__c</fullName>
    <formula>If(
AND(
Case__r.Protocol__r.Unilateral_referral_days__c =0,Unilateral_referral_date__c  &lt;= Today()),true,
If(OR(Unilateral_referral_date__c  &gt;= Today(),ISNULL(Unilateral_referral_date__c) ),
false,true))</formula>
    <label>Unilateral referral date passed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CaseReferalHandler.cls
Public Class CaseReferalHandler{



public static void UpdatetoDocPrepStatus(Set<String> Set_CaseID){
    
       system.debug('**Set_CaseID**'+Set_CaseID); 
        
     List<Schedule_of_Losses__c> ScheduleofLosses = new List<Schedule_of_Losses__c>([Select id,Unilateral_referral_date__c,Doc_Prep_Start_Date__c,Defendant_Accept_Decline__c,Claimant_Accept_Decline__c,Claimaint_Arbitration_Submitted__c,Defendant_Arbitration_Submitted__c, Bilateral_referral_date_passed__c,No_referral_date_passed__c,Unilateral_referral_date_passed__c 
                         From Schedule_of_Losses__c Where Case__c in: Set_CaseID 
                         AND Bilateral_referral_date_passed__c=:true
                         AND Unilateral_Arbitration_Overlap__c =: false
                         AND Unilateral_referral_date_passed__c =:true
                         AND Doc_Prep_Start_Date__c=:null]);
        
        
      List<Loss_Category__c> LossCategory =  new List<Loss_Category__c>([SELECT id,Schedule_of_Losses__c,Loss_Category_Types__r.Name FROM Loss_Category__c where Schedule_of_Losses__c in:ScheduleofLosses]);
      List<Loss_Sub_Categories__c> LossSubCategories  = new List<Loss_Sub_Categories__c>([SELECT Id,Arbitration_Referred_By__c,Arbitration_Accepted_Status__c,Past_Future_Financial_Item__c, Sub_Category__c,Defendant_Position__c,Loss_Category__c,Sum_Defendent_Position__c,Stage__c,Status__c,Claimant_Position__c,Arbitrator_Award__c,Name,Past_Future_Financial_Losses__r.Name,RecordType.DeveloperName FROM Loss_Sub_Categories__c WHERE (Status__c = 'Negotiating' OR Status__c = 'Referred to Arbitration' ) AND Loss_Category__c in:  LossCategory ]);
      List<Merit__c> lstMerit = new List<Merit__c>([Select id,Status__c,Arbitration_Accepted_Status__c,Defendant_Position__c,Arbitration_Referred_By__c, Arbitrator_Award__c,Related_Case__c, Claimant_Position__c, name, Schedule_of_Losses__c From Merit__c where Schedule_of_Losses__c in: ScheduleofLosses and (Status__c='Negotiating' OR Status__c='Referred to Arbitration')]);
      
      
        
      for(Schedule_of_Losses__c s:ScheduleofLosses){
              s.Doc_Prep_Start_Date__c = system.today();
              s.Defendant_Accept_Decline__c=true;
              s.Claimant_Accept_Decline__c=true;
              s.Claimaint_Arbitration_Submitted__c=true;
              s.Defendant_Arbitration_Submitted__c=true;                     
      }  
      
      for(Loss_Sub_Categories__c c:LossSubCategories){
          c.Status__c='Arbitration Doc Prep';
          c.Arbitration_Accepted_Status__c ='Accepted';
      }
      update LossSubCategories;
      
      
      for(Merit__c m:lstMerit){
          m.Arbitration_Accepted_Status__c   = 'Accepted';
          m.Status__c = 'Arbitration Doc Prep';
      }   
      
      update lstMerit;
      
      update ScheduleofLosses;
        
}

public static void UpdatetoFinalOffersStatus(Set<String> Set_CaseID){
    
    system.debug('**Set_CaseID**'+Set_CaseID); 
        
     List<Schedule_of_Losses__c> ScheduleofLosses = new List<Schedule_of_Losses__c>([Select id,Invite_Arbitrator__c,Doc_Prep_End_Date__c,Defendant_Accept_Decline__c,Claimant_Accept_Decline__c,Claimaint_Arbitration_Submitted__c,Defendant_Arbitration_Submitted__c, Bilateral_referral_date_passed__c,No_referral_date_passed__c,Unilateral_referral_date_passed__c 
                         From Schedule_of_Losses__c Where Case__c in: Set_CaseID 
                        
                         AND Bilateral_referral_date_passed__c=:True
                         AND Doc_Prep_Date_passed__c =:true
                         AND Final_Offers_Start_Date__c =: null
                         ]);
        
        
      List<Loss_Category__c> LossCategory =  new List<Loss_Category__c>([SELECT id,Schedule_of_Losses__c,Loss_Category_Types__r.Name FROM Loss_Category__c where Schedule_of_Losses__c in:ScheduleofLosses]);
      List<Loss_Sub_Categories__c> LossSubCategories  = new List<Loss_Sub_Categories__c>([SELECT Id,Arbitration_Referred_By__c,Arbitration_Accepted_Status__c,Past_Future_Financial_Item__c, Sub_Category__c,Defendant_Position__c,Loss_Category__c,Sum_Defendent_Position__c,Stage__c,Status__c,Claimant_Position__c,Arbitrator_Award__c,Name,Past_Future_Financial_Losses__r.Name,RecordType.DeveloperName FROM Loss_Sub_Categories__c WHERE (Status__c = 'Arbitration Doc Prep' ) AND Loss_Category__c in:  LossCategory ]);
      List<Merit__c> lstMerit = new List<Merit__c>([Select id,Status__c,Arbitration_Accepted_Status__c,Defendant_Position__c,Arbitration_Referred_By__c, Arbitrator_Award__c,Related_Case__c, Claimant_Position__c, name, Schedule_of_Losses__c From Merit__c where Schedule_of_Losses__c in: ScheduleofLosses and Status__c='Arbitration Doc Prep']);
      
      for(Loss_Sub_Categories__c c:LossSubCategories){
          c.Status__c='Arbitration Final Offers';
      }
      update LossSubCategories;
      
      
      for(Merit__c m:lstMerit){
          m.Status__c = 'Arbitration Final Offers';
      }   
      
      update lstMerit;
        
      for(Schedule_of_Losses__c s:ScheduleofLosses){
          
           
              s.Claimant_Confirm_Documents_Uploaded__c=true;
              s.Defendant_Confirm_Documents_uploaded__c=true; 
              s.Final_Offers_Start_Date__c = system.today(); 
              s.Invite_Arbitrator__c = true;    
          
      }  
      
      update ScheduleofLosses;
      
      
      
}


public static void UpdatetoArbitratingStatus(Set<String> Set_CaseID){
    
    system.debug('**Set_CaseID**'+Set_CaseID); 
     List<Schedule_of_Losses__c> ScheduleofLosses = new List<Schedule_of_Losses__c>([Select id,Defendant_Accept_Decline__c,Claimant_Accept_Decline__c,Claimaint_Arbitration_Submitted__c,Defendant_Arbitration_Submitted__c, Bilateral_referral_date_passed__c,No_referral_date_passed__c,Unilateral_referral_date_passed__c 
                         From Schedule_of_Losses__c Where Case__c in: Set_CaseID 
                         AND Bilateral_referral_date_passed__c=:True
                         AND Doc_Prep_Date_passed__c =:true
                         AND Final_Offers_Date_passed__c =:true
                         AND Arbitration_Start_Date__c =: null
                         ]);
        
        
      List<Loss_Category__c> LossCategory =  new List<Loss_Category__c>([SELECT id,Schedule_of_Losses__c,Loss_Category_Types__r.Name FROM Loss_Category__c where Schedule_of_Losses__c in:ScheduleofLosses]);
      List<Loss_Sub_Categories__c> LossSubCategories  = new List<Loss_Sub_Categories__c>([SELECT Id,Arbitration_Referred_By__c,Arbitration_Accepted_Status__c,Past_Future_Financial_Item__c, Sub_Category__c,Defendant_Position__c,Loss_Category__c,Sum_Defendent_Position__c,Stage__c,Status__c,Claimant_Position__c,Arbitrator_Award__c,Name,Past_Future_Financial_Losses__r.Name,RecordType.DeveloperName FROM Loss_Sub_Categories__c WHERE (Status__c = 'Arbitration Final Offers' ) AND Loss_Category__c in:  LossCategory ]);
      List<Merit__c> lstMerit = new List<Merit__c>([Select id,Status__c,Arbitration_Accepted_Status__c,Defendant_Position__c,Arbitration_Referred_By__c, Arbitrator_Award__c,Related_Case__c, Claimant_Position__c, name, Schedule_of_Losses__c From Merit__c where Schedule_of_Losses__c in: ScheduleofLosses and Status__c='Arbitration Final Offers']);
      
      for(Loss_Sub_Categories__c c:LossSubCategories){
          c.Status__c='Arbitrating';
      }
      update LossSubCategories;
      
      
      for(Merit__c m:lstMerit){
          m.Status__c = 'Arbitrating';
      }   
      
      update lstMerit;
        
        
      for(Schedule_of_Losses__c s:ScheduleofLosses){
          s.Claimant_Final_Offer_Confirmed__c=true;
          s.Defendant_Final_Offer_Confirmed__c  =true;
          s.Arbitration_Start_Date__c = system.today(); 
               
      }  
      
      update ScheduleofLosses;
      
      
      
        
}


}