force-app/main/default/objects/Account/fields/FirmID__c.field-meta.xml
<CustomField>
    <fullName>FirmID__c</fullName>
    <label>FirmID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/Case_Staging_Table__c.object-meta.xml
<CustomObject>
    <label>Case Staging Table</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Case Staging id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Staging Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Staging_Table__c/fields/Case_Source__c.field-meta.xml
<CustomField>
    <fullName>Case_Source__c</fullName>
    <label>Case Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Claimant</fullName>
            </value>
            <value>
                <fullName>Defendant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Claimant_Firm_ID__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Firm_ID__c</fullName>
    <label>Claimant Firm ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Claimant_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Claimant_Reference_Number__c</fullName>
    <label>Claimant Reference Number</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Defendant_Firm_ID__c.field-meta.xml
<CustomField>
    <fullName>Defendant_Firm_ID__c</fullName>
    <label>Defendant Firm ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Firm_Team__c</fullName>
    <label>Firm Team</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Import_Key__c.field-meta.xml
<CustomField>
    <fullName>Import_Key__c</fullName>
    <formula>TEXT(Incident_Date__c)&amp;IF (ISBLANK(Incident_Post_Code__c) = TRUE , &apos;&apos;, LEFT(Incident_Post_Code__c, 3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Import Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Incident_Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Incident_Post_Code__c</fullName>
    <label>Incident Post Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Incident_Post_Code_Shorten__c.field-meta.xml
<CustomField>
    <fullName>Incident_Post_Code_Shorten__c</fullName>
    <formula>IF (ISBLANK(Incident_Post_Code__c) = TRUE , &apos;&apos;, LEFT(Incident_Post_Code__c, 3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incident Post Code Shorten</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Mapped_Claimant_Firm__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Claimant_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mapped Claimant Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Staging Table (Mapped Claimant Firm)</relationshipLabel>
    <relationshipName>Case_Staging_Table1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Mapped_Defendant_Firm__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Defendant_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mapped Defendant Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Case Staging Table</relationshipLabel>
    <relationshipName>Case_Staging_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Mapped_Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Firm_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mapped Firm Team</label>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Case Staging Table</relationshipLabel>
    <relationshipName>Case_Staging_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Mapped_Incident__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Incident__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mapped Incident</label>
    <referenceTo>Incident_Information__c</referenceTo>
    <relationshipLabel>Case Staging Table</relationshipLabel>
    <relationshipName>Case_Staging_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Mapped_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mapped Protocol</label>
    <referenceTo>Protocol__c</referenceTo>
    <relationshipLabel>Case Staging Table</relationshipLabel>
    <relationshipName>Case_Staging_Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Mapped_Status__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Status__c</fullName>
    <label>Mapped Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Mapped_Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>Mapped_Status_Detail__c</fullName>
    <label>Mapped Status Detail</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Merit_Claimant_Position__c.field-meta.xml
<CustomField>
    <fullName>Merit_Claimant_Position__c</fullName>
    <label>Merit Claimant Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case_Staging_Table__c/fields/Protocol_Code__c.field-meta.xml
<CustomField>
    <fullName>Protocol_Code__c</fullName>
    <label>Protocol Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Firm_Team__c/Firm_Team__c.object-meta.xml
<CustomObject>
    <label>Firm Team</label>
    <nameField>
        <label>Firm Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firm Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Firm_Team__c/fields/Firm__c.field-meta.xml
<CustomField>
    <fullName>Firm__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Firm Teams</relationshipLabel>
    <relationshipName>Firm_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Firm_Team__c/fields/Firm_ID__c.field-meta.xml
<CustomField>
    <fullName>Firm_ID__c</fullName>
    <formula>Firm__r.FirmID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Incident_Information__c/Incident_Information__c.object-meta.xml
<CustomObject>
    <label>Incident Information</label>
    <nameField>
        <displayFormat>Incident - {000000}</displayFormat>
        <label>Incident Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Incident_Information__c/fields/Incident_Date__c.field-meta.xml
<CustomField>
    <fullName>Incident_Date__c</fullName>
    <label>Incident Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Incident_Information__c/fields/Incident_Key__c.field-meta.xml
<CustomField>
    <fullName>Incident_Key__c</fullName>
    <formula>TEXT( Incident_Date__c )&amp;IF (ISBLANK(Postal_Code__c ) = TRUE , &apos;&apos;, LEFT(Postal_Code__c, 3))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incident Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Protocol__c/Protocol__c.object-meta.xml
<CustomObject>
    <label>Protocol</label>
    <nameField>
        <label>Protocol Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseMatchingUtility.cls
Public Class CaseMatchingUtility{
@InvocableMethod


  Public static void ProcessImportedData (List<Id> ids){
  
      Map <Id, String> CaseProtocolMap = new Map<id, String>();
      Map<id, String> CaseCRMap = new Map<id, String>();
      Map<id, String> CaseDRMap = new Map<id, String>();
      Map<id, String> CaseCRTeamMap = new Map<id, String>();
      Map<id, Date> CaseIncidentDate = new Map<id, Date>();
      Map<id, String> CaseIncidentPostCode = new Map<id,String>();
      Map<String,id> CaseIncidentDatePostCodeMap = new Map<String, id>();
      Map<Id, id> CaseIncidentMap = New Map<Id, Id>() ; 
      Map <String, Id> ProtocolMap = new Map<String, Id>();
      Map <String, Id> CRMap = new Map<String, Id>();
      Map <String, Id> FirmMap = new Map<String, Id>();
      Map <String, Id> FirmTeamMap = new Map<String, Id>();
      Map <String, String > Firm2TeamMap = new Map<String,String>();
      Set<String> CaseProtocolSet = new Set<String>();
      Set<String> CaseCRSet = new Set<String>();
      Set<Date> dtIncidentDateSet = new Set<Date>();
      Set<String> IncidentPostCodeSet = new Set <String>();
      Set<String> IncidentPostCode = new Set<String>();
      Set<String> IncidentDatePostCode = new Set<String>(); 
      Set<id> FirmSet = new Set<Id>();
      
     /* SELECT Firm__c, id, name FROM Firm_Team__c*/
         
      String Recordid = '';
      List<Case_Staging_Table__c> CaseStagingtoUpdate = new  List<Case_Staging_Table__c>();
      String ImportErrors = '';
      Date dtIncidentDate = null;
           
      For (Protocol__c p:  [SELECT id, Code__c FROM Protocol__c ]){
          ProtocolMap.put(p.Code__c, p.Id);  
      }
       For (Account a:  [SELECT id, Name,FirmID__c FROM Account ]){
          FirmMap.put(a.FirmID__c, a.Id); 
          //FirmMap.put(a.FIRM_ID__C, a.Id);  
        //  System.Debug('## FirmMap.put ' + a.FIRM_ID__C + ' ' + a.id +' ##');
         /* FirmSet.Add ( a.Id);*/
      }
       For (Firm_Team__c ft:  [SELECT id, Name, Firm__c FROM Firm_Team__c  ]){
          FirmTeamMap.put(ft.Name, ft.Id);       
          System.Debug('## FirmTeamMap.put ' + ft.Name + ' ' + ft.id +' ##');
          
          Firm2TeamMap.put(ft.Name + '_' + ft.firm__c, ft.id );
          System.Debug('#$$# Firm2TeamMap.put ' + ft.Name + '_' +  ft.firm__c +' #$$#'); 
      }
        
       
      For (Case_Staging_Table__c cst : [SELECT Case_Number__c,Case_Source__c,Claimant_Firm_ID__c, Defendant_Firm_ID__c,Protocol_Code__c,
                         Incident_Date__c,
                         Incident_Post_Code__c,Incident_Post_Code_Shorten__c,Address_Line_1__c, Address_Line_2__c,
                                        Mapped_Protocol__c, Mapped_Defendant_Firm__c,   Mapped_Incident__c, Mapped_Status__c, Import_Key__c,
                                        Firm_Team__c, Claimant_Reference_Number__c,Merit_Claimant_Position__c, Mapped_Firm_Team__c 
                                        FROM Case_Staging_Table__c where Id in : ids]){
           CaseStagingtoUpdate.add (cst);
                                         
           if( !CaseProtocolSet.contains(cst.Protocol_Code__c)){                
               CaseProtocolSet.add(cst.Protocol_Code__c) ;
           }
                  
           if (cst.Import_Key__c !=null)  {
             if ( !IncidentDatePostCode.contains(cst.Import_Key__c )){
                 IncidentDatePostCode.add(cst.Import_Key__c); 
             }
           }                        
                                             
           CaseProtocolMap.put(cst.id, cst.Protocol_Code__c); 
           CaseCRMap.put(cst.id, cst.Claimant_Firm_ID__c);
           System.Debug('## CaseCRMap.put ' + cst.id + ' ' + cst.Claimant_Firm_ID__c + ' ##');
           CaseCRTeamMap.put(cst.id, cst.Firm_Team__c);
           System.Debug('## CaseCRTeamMap.put ' + cst.id + ' ' + cst.Firm_Team__c + ' ##');
           CaseDRMap.put(cst.id, cst.Defendant_Firm_ID__c); 
           CaseIncidentDatePostCodeMap.put(cst.Import_Key__c, cst.id);  
           System.Debug('#$# CaseIncidentDatePostCodeMap ' + cst.Import_Key__c + ' ' + cst.id + ' ##');                                                                                  
      }
      
      /* Check to see if the Incident exists based on Incident Date and Incident Post Code*/
      For (Incident_Information__c inc : [Select id ,Incident_Key__c from Incident_Information__c  where  Incident_Key__c in : IncidentDatePostCode  ]){
            System.Debug('#$$# Incident ID to Date Post Code Map ' +   inc.id + ' ' + inc.Incident_Key__c  + ' ###'); 
            String CaseStageid =  CaseIncidentDatePostCodeMap.get(inc.Incident_Key__c);
            CaseIncidentMap.put(CaseStageid, inc.Id);                                                                
      }
      
    
    
      
      For (Case_Staging_Table__c cst1 : CaseStagingtoUpdate ){
          String cstid = cst1.id;
          System.Debug('## cstid ' + cstid + ' ##');
          System.Debug('## CaseProtocolMap.get ' + CaseProtocolMap.get(cst1.id) + ' ##');
          System.Debug('## CaseProtocolMap.get 2 ' + ProtocolMap.get(CaseProtocolMap.get(cst1.id)) + ' ##');
          
          System.Debug('## CaseCRMap.get ' + CaseCRMap.get(cst1.id) + ' ##');
          System.Debug('## CaseCRMap.get 2 ' + FirmMap.get(CaseCRMap.get(cst1.id)) + ' ##');
        
          
          If (CaseProtocolMap.get(cst1.id) != null){
              cst1.Mapped_Protocol__c = ProtocolMap.get(CaseProtocolMap.get(cst1.id)); 
          }
          If (CaseCRMap.get(cst1.id) != null){
              cst1.Mapped_Claimant_Firm__c = FirmMap.get(CaseCRMap.get(cst1.id)); 
          }      
          If (CaseCRTeamMap.get(cst1.id) != null){
              String Firm2Team = CaseCRTeamMap.get(cst1.id) + '_' + cst1.Mapped_Claimant_Firm__c ;
            /*  cst1.Mapped_Firm_Team__c = FirmTeamMap.get(CaseCRTeamMap.get(cst1.id));*/
             System.Debug('#$$$# Firm2Team output ' + Firm2Team + '#$$$#');
            
              cst1.Mapped_Firm_Team__c  = Firm2TeamMap.get (Firm2Team ); 
          }
          If (CaseDRMap.get(cst1.id) != null){
              cst1.Mapped_Defendant_Firm__c = FirmMap.get(CaseDRMap.get(cst1.id)); 
          }
          If (CaseIncidentMap.get(cst1.id) != null){
              cst1.Mapped_Incident__c = CaseIncidentMap.get(cst1.id); 
          }
          
          
          /* Check if mapping is successfully or not */
          if (cst1.Mapped_Protocol__c != null  && cst1.Mapped_Firm_Team__c !=null && cst1.Mapped_Claimant_Firm__c != null  && cst1.Mapped_Defendant_Firm__c != null &&  cst1.Mapped_Incident__c == null ){
             cst1.Mapped_Status__c = 'Accepted'; 
          }
          else{
             cst1.Mapped_Status__c = 'Rejected';
             String MappingError = ''; 
             if (cst1.Mapped_Protocol__c == null) {
                MappingError  += 'Protocol not found' + '\n';
             }
             if (cst1.Mapped_Claimant_Firm__c == null) {
                MappingError  += 'Claimant not found'+ '\n';
             }
             if (cst1.Mapped_Firm_Team__c == null) {
                MappingError  += 'Claimant Firm Team not found'+ '\n';
             }
             if (cst1.Mapped_Defendant_Firm__c == null) {
                MappingError  += 'Defendant not found'+ '\n';
             }
             if (cst1.Mapped_Incident__c != null) {
                MappingError  += 'Existing Incident found'+ '\n';
             }
             cst1.Mapped_Status_Detail__c = Mappingerror;
          }
             
      }
      
      If (CaseStagingtoUpdate.IsEmpty() != null){
         update CaseStagingtoUpdate;
      }
      
  }
  
  
 
                                        
     
   /*
   List<Opportunity> oppLst = [Select o.CreatedDate, o.Id from Opportunity o where   o.CreatedDate >: myDate and o.CreatedDate <:  myDate2 order by  o.LastModifiedDate] ;
   */
  
}