force-app/main/default/objects/Contact/fields/Active_Case_on_Individual_Count__c.field-meta.xml
<CustomField>
    <fullName>Active_Case_on_Individual_Count__c</fullName>
    <label>Active Case on Individual Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Handler</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Arbitrator</fullName>
            </value>
            <value>
                <fullName>Facilitator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Firm_Team__c/Firm_Team__c.object-meta.xml
<CustomObject>
    <label>Firm Team</label>
    <nameField>
        <label>Firm Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firm Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Firm_Team__c/fields/Firm__c.field-meta.xml
<CustomField>
    <fullName>Firm__c</fullName>
    <label>Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Firm Teams</relationshipLabel>
    <relationshipName>Firm_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Firm_Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Firm_Team_Roles__c/Firm_Team_Roles__c.object-meta.xml
<CustomObject>
    <label>Firm Team Role</label>
    <nameField>
        <displayFormat>FTR- {0000}</displayFormat>
        <label>Firm Team Roles Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Firm Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Firm_Team_Roles__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Role__c</field>
            <operation>equals</operation>
            <value>Handler</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Firm Team Roles</relationshipLabel>
    <relationshipName>Firm_Team_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Firm_Team_Roles__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact__r.FirstName + &apos; &apos; +  Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Firm_Team_Roles__c/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <formula>TEXT(Contact__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Firm_Team_Roles__c/fields/Firm_Team__c.field-meta.xml
<CustomField>
    <fullName>Firm_Team__c</fullName>
    <label>Firm Team</label>
    <referenceTo>Firm_Team__c</referenceTo>
    <relationshipLabel>Firm Team Roles</relationshipLabel>
    <relationshipName>Firm_Team_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Firm_Team_Roles__c/fields/Firm_Team_Name__c.field-meta.xml
<CustomField>
    <fullName>Firm_Team_Name__c</fullName>
    <formula>Firm_Team__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Firm Team Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Firm_Team_Roles__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case Handler</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
                <isActive>false</isActive>
                <label>Supervisor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TeamViewApexController.cls
public class TeamViewApexController {
    
    @AuraEnabled
    public static List<FirmTeamWrapper> getFirmTeamRoles() {
        
        User[] ContactUser =[Select id,ContactId, AccountId From user where id=:UserInfo.getUserId()];
        Contact[] lstContact = [Select id,Active_Case_on_Individual_Count__c,AccountId,Role__c,Name,Email,Status__c From Contact where id =:ContactUser[0].ContactId];
        Firm_Team__c[] lstFirmTeam = [Select id,Firm__c,Name from Firm_Team__c where Firm__c=:lstContact[0].AccountId]; 
        Set<String> Set_Han = new Set<String>();
        List<FirmTeamWrapper> firmTeamList = new List<FirmTeamWrapper>();
        List<Contact> firmContacts = [SELECT Id, AccountId, Name, Email, Role__c, Status__c FROM Contact WHERE AccountId =:lstContact[0].AccountId ];
        for( Contact con:firmContacts){
            if(con.Role__c=='Handler'){
                Set_Han.add(con.id);    
            }
        }
            Firm_Team_Roles__c[] FirmTeamRoles = [Select Firm_Team__c,Firm_Team_Name__c,Contact_Email__c, Contact_Name__c,Roles__c, Contact__c, Contact_Status__c   From Firm_Team_Roles__c where  Contact__c in: Set_Han];
            
            
            
            Map<String,String> Map_TeamName = new Map<String,String>();
            
            for(Firm_Team_Roles__c role : FirmTeamRoles){
                Map_TeamName.put(role.Contact__c,role.Firm_Team_Name__c);
                    }
            
            
            for( Contact con2 : firmContacts){
                FirmTeamWrapper teamwrap = new FirmTeamWrapper();
                if(con2.Role__c=='Handler'){
                    system.debug('***TeAM**'+Map_TeamName.get(con2.id));
                    teamwrap.Team =Map_TeamName.get(con2.id);         
                }
                else{
                    teamwrap.Team ='';
                }
                teamwrap.Name = con2.Name;
                teamwrap.Email = con2.Email;
                teamwrap.Role = con2.Role__c;
                teamwrap.Status = con2.Status__c;
                
                firmTeamList.add(teamwrap);
                
            }
        
            
            
        
        return firmTeamList;
    }
    
        
        
        
        
        public Class FirmTeamWrapper{
            @AuraEnabled
            public String Team {get; set;}
            @AuraEnabled
            public String Name {get; set;}
            @AuraEnabled
            public String Email {get; set;}
            @AuraEnabled
            public String Role {get; set;}
            @AuraEnabled
            public String Status {get; set;}
        }
        
    }