force-app/main/default/objects/Firm_Team__c/Firm_Team__c.object-meta.xml
<CustomObject>
    <label>Firm Team</label>
    <nameField>
        <label>Firm Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firm Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Firm_Team__c/fields/Active_Case_Count__c.field-meta.xml
<CustomField>
    <fullName>Active_Case_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Active Case Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Firm_Team__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FromFirmTeam_Deactivate_test.cls
@istest

Public class FromFirmTeam_Deactivate_test{


Public static testmethod void FromFirmTeamDeactivate1(){

    test.starttest();
    Test_InsertFirm_Contact_Team_TeamRole.insertContactUser('testINAPSOL1@noemail.com','SOL1');
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser2();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser3();
            
            Test_InsertFirm_Contact_Team_TeamRole.insertContactUser4();
       StatusChangeHandler.STATUSCHANGETRIGGER = false;
       Firm_Team__c[] lstFirmTeam = [Select id,Active_Case_Count__c from Firm_Team__c where Status__c ='Active' ];    
       lstFirmTeam[0].Status__c ='Inactive';
       Update lstFirmTeam;
    
    test.stoptest();
    

}



}