force-app/main/default/objects/Firm_Team__c/Firm_Team__c.object-meta.xml
<CustomObject>
    <label>Firm Team</label>
    <nameField>
        <label>Firm Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firm Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Firm_Team__c/fields/Deactivate_Validation__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FromFirmTeam_Remove.cls
Public Class FromFirmTeam_Remove{


//@invocablemethod
Public static Boolean RemoveAllMembers(List<Id> FirmTeam){
    
     
    Boolean Active=FirmMemberTeamHandler.CheckForActiveTeam(FirmTeam);
    
    if(Active){
        /*
        Firm_Team__c[] lstFirmTeam = [Select id,Deactivate_Validation__c  from Firm_Team__c where id in:FirmTeam];
        
        for(Firm_Team__c firm:lstFirmTeam){
            firm.Deactivate_Validation__c=true;
        }    
        update lstFirmTeam;
        */
    }
    else{    
        FirmMemberTeamHandler.RemoveAllmembersinteam(FirmTeam);
    }  
    
    return Active;  
}


}